<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>HPS201: Psychology Research Methods (Introductory)</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">BPsychSci</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-list fa-lg"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-book fa-lg"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="HBS110.html">HBS110</a>
    </li>
    <li>
      <a href="HPS104.html">HPS104</a>
    </li>
    <li>
      <a href="HPS105.html">HPS105</a>
    </li>
    <li>
      <a href="HPS111.html">HPS111</a>
    </li>
    <li>
      <a href="HPS121.html">HPS121</a>
    </li>
    <li>
      <a href="HPS201.html">HPS201</a>
    </li>
    <li>
      <a href="HPS202.html">HPS202</a>
    </li>
    <li>
      <a href="HPS203.html">HPS203</a>
    </li>
    <li>
      <a href="HPS204.html">HPS204</a>
    </li>
    <li>
      <a href="HSH105.html">HSH105</a>
    </li>
    <li>
      <a href="HSH206.html">HSH206</a>
    </li>
    <li>
      <a href="SIT191.html">SIT191</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">HPS201: Psychology Research Methods
(Introductory)</h1>

</div>


<div id="week-1-measurement" class="section level2 well">
<h2 class="well">Week 1: Measurement</h2>
<div id="lo1-understand-the-difference-between-population-and-sample"
class="section level3 well">
<h3 class="well">LO1: Understand the difference between population and
sample</h3>
<div id="population-vs.-sample" class="section level4">
<h4>Population vs. Sample</h4>
<p><strong>Population:</strong> the entire set of individuals, or
events, of interest in a particular study (Often not feasible!)
<strong>Sample:</strong> set of individuals selected from a
population</p>
</div>
<div id="example" class="section level4">
<h4>Example:</h4>
<p>A psychologist wants to determine whether a motivational program is
effective in improving work performance in Australian office
workers.</p>
<ul>
<li>Population: Every Australian office worker</li>
<li>Problem?: Not feasible, and not sure if it works yet.</li>
<li>Solution: Select a sample from the population Sample (e.g., 100
workers from each state)</li>
<li>Generalise: Results from the sample (100 workers from each state)
back to the population of interest (Every Australian Office Worker)</li>
</ul>
</div>
</div>
<div id="lo2-distinguish-between-parameters-and-statistics"
class="section level3 well">
<h3 class="well">LO2: Distinguish between parameters and statistics</h3>
<p><strong>Parameter:</strong> a value that describes a key
characteristic of the population, such as:</p>
<ul>
<li>Average income of all Australians</li>
<li>Average age of all Australians</li>
</ul>
<p><strong>Statistic:</strong> a value that describes a key
characteristic of the sample, such as:</p>
<ul>
<li>Average IQ of a sample of 1000 Australian Uni Students</li>
<li>Average Age of a sample of 1000 Australian Uni Students</li>
</ul>
<p><span class="math inline">\(\bigstar\)</span> Statistics are used to
estimate values that exist in the population.</p>
</div>
<div id="lo3-distinguish-between-descriptive-and-inferential-statistics"
class="section level3 well">
<h3 class="well">LO3: Distinguish between descriptive and inferential
statistics</h3>
<p>As a researcher, you have:</p>
<ul>
<li>Decided on a research question: Is a new anti-depressant effective
at reducing depressive symptoms?</li>
<li>You’ve taken a sample of individuals to answer your research
question: 100 individuals with depression</li>
<li>Conduct your experiment
<ul>
<li>50 given the new anti-depressant</li>
<li>50 given the pre-existing best seller</li>
</ul></li>
<li>Measure depression levels after (0-100)</li>
<li>You’ve collected your data. Now what??</li>
</ul>
<p>Statistics is the method of using mathematics to organize, summarise,
and interpret numerical data</p>
<p>Two main types:</p>
<div id="descriptive-statistics" class="section level4">
<h4>Descriptive statistics:</h4>
<ul>
<li>Simply used to describe data (Weeks 1 and 2)</li>
<li>Summarize data</li>
<li>Averages, score ranges etc.</li>
<li>Makes data manageable</li>
</ul>
</div>
<div id="inferential-statistics" class="section level4">
<h4>Inferential statistics:</h4>
<ul>
<li>Used when we want to answer research questions (Week 3 onwards)</li>
<li>Allows us to make generalisations from our sample to our population
of interest</li>
</ul>
</div>
</div>
<div id="lo4-distinguish-between-discrete-and-continuous-variables"
class="section level3 well">
<h3 class="well">LO4: Distinguish between discrete and continuous
variables</h3>
<ul>
<li>Before we can answer our research questions we need data</li>
<li>Data is obtained by measuring specific variables of interest to your
research question</li>
<li><strong>Variable:</strong> a characteristic or condition that
changes or has different values for different individuals (Previous
example: Depression, Age, etc.)</li>
</ul>
<div id="discrete-data" class="section level4">
<h4>Discrete data</h4>
<ul>
<li>Contain only a small number of values, such as:
<ul>
<li>handedness (right/left/ambidextrous)</li>
<li>favourite season (summer/autumn/ winter/ spring)</li>
</ul></li>
<li>Often referred to as Categorical data</li>
</ul>
</div>
<div id="continuous" class="section level4">
<h4>Continuous:</h4>
<p>Continuous variables contain many different values - Weight (40kg-
140kg), age (0-100 years)</p>
<ul>
<li>Are often referred to as Measurement data</li>
<li>Often depends on the way you set up the measurement.</li>
<li>e.g. Anxiety levels of HPS201/771 students</li>
</ul>
</div>
<div id="discrete-or-continuous" class="section level4">
<h4>Discrete or continuous?</h4>
<ul>
<li>Continuous variables can represent a score on a scale (e.g. an
anxiety questionnaire)</li>
<li>Questionnaire scores range from 0-60</li>
<li>Discrete variables allow for people to be organised into groups:
<ul>
<li>High anxiety (41-60)</li>
<li>Average anxiety (21-40)</li>
<li>Low anxiety (0-20)</li>
</ul></li>
</ul>
</div>
<div id="why-does-it-matter" class="section level4">
<h4>Why does it matter?</h4>
<p><strong>The type of data that you use will impact the types of
statistical approach that we use to analyse data</strong></p>
<ul>
<li>Continuous/Measurement data are usually summarised using means
(e.g. Mean age of HPS201 students is 19.8, Mean height of AFL
footballers is 188cm)</li>
<li>Discrete/Categorical data are usually summarized using percentage
(e.g. 15% of participants were left-handed, 75% right-handed, 10%
ambidextrous. 32% of students have black hair, 8% have red hair, 50%
have brown hair, 5 % have blonde hair, 5% other)</li>
</ul>
</div>
</div>
<div
id="lo5-explain-the-difference-between-categorical-data-and-measurement-data"
class="section level3 well">
<h3 class="well">LO5: Explain the difference between categorical data
and measurement data</h3>
<p>The type of data that you use will impact the types of statistical
approach that we use to analyse data.</p>
<p>Continuous/Measurement data are usually summarised using means
(averages)</p>
<ul>
<li>Mean age of HPS201 students is 19.8 (made up)</li>
<li>Mean height of AFL footballers is 188cm</li>
</ul>
<p>Discrete/Categorical data are usually summarized using percentage</p>
<ul>
<li>15% of participants were left-handed, 75% right-handed, 10%
ambidextrous</li>
<li>32% if students have black hair, 8% have red hair , 50% have brown
hair, 5 % have blonde hair, 5% other</li>
</ul>
</div>
<div id="lo6-distinguish-between-independent-and-dependent-variables"
class="section level3 well">
<h3 class="well">LO6: Distinguish between independent and dependent
variables</h3>
<div id="independent-variable-iv-x-axis" class="section level4">
<h4>Independent variable (IV / X-axis):</h4>
<ul>
<li>The variable that we manipulate</li>
<li>As a researcher, we believe that the IV will effect our dependent
variable</li>
</ul>
</div>
<div id="dependent-variable-dv-y-axis" class="section level4">
<h4>Dependent variable (DV / Y-axis):</h4>
<ul>
<li>The variable that we measure</li>
<li>The variable that is observed for differences/changes #### Quiz
time!</li>
</ul>
<p>A researcher wanted to test her theory that people tend to walk
faster on cold days compared to hot days…</p>
<p><abbr title="Type of day (hot vs cold)">Independent
variable?</abbr></p>
<p><abbr title="Walking speed">Dependant variable?</abbr> #### Quiz
time!</p>
<p>A psychologist wants to investigate whether caffeine improves
attention. She gives different amounts of caffeine (low or high) to the
research participants and then measures their attentional capacity…</p>
<p><abbr title="Amount of caffeine">Independent variable?</abbr></p>
<p><abbr title="Attentional Capacity">Dependant variable?</abbr></p>
</div>
</div>
<div
id="lo7-understand-the-different-types-of-measurement-scales-nominal-ordinal-interval-and-ratio"
class="section level3 well">
<h3 class="well">LO7: Understand the different types of measurement
scales (nominal, ordinal, interval and ratio)</h3>
<p>We measure our IV and DV’s using a variety of measurement scales:</p>
<ul>
<li><p><strong>Nominal:</strong> consist of a set of categories with
different names in no ordered sequence</p>
<ul>
<li>Handedness:
<ul>
<li>Right, Left, Ambidextrous</li>
<li>No category is higher/lower, better/worse than any other as they are
just labels for different categories</li>
</ul></li>
</ul></li>
<li><p><strong>Ordinal:</strong> Ordinal scales consist of a set of
categories with different names AND are organized into an ordered
sequence</p>
<ul>
<li>Highest level of academic qualification:
<ul>
<li>High School Incomplete</li>
<li>High School Complete</li>
<li>Diploma</li>
<li>Bachelor Degree</li>
<li>Masters Degree</li>
<li>PhD</li>
</ul></li>
</ul></li>
<li><p><strong>Interval:</strong> Consist of ordered categories where
the intervals are exactly the same size</p>
<ul>
<li>The distance between each value is the same along the scale</li>
<li>Usually have a more data points than ordinal scales (continuous
data)</li>
<li><strong>No absolute zero point</strong>
<ul>
<li>Degrees Celsius</li>
<li>Distance between 10-15 degrees is the same as the distance between
30-35 degrees</li>
<li>Zero degrees does not represent the absence of temperature. It is
just a point on the temperature scale</li>
</ul></li>
</ul></li>
<li><p><strong>Ratio:</strong> Consist of ordered categories where the
intervals are exactly the same size</p>
<ul>
<li>The distance between each value is the same along the scale</li>
<li>Usually have a more data points than ordinal scales (continuous
data)</li>
<li><strong>With a true zero point</strong>
<ul>
<li>Time (minutes)</li>
<li>length (cm)</li>
</ul></li>
</ul></li>
</ul>
</div>
<div
id="l08-understand-how-to-construct-frequency-distributions-and-histograms"
class="section level3 well">
<h3 class="well">L08: Understand how to construct frequency
distributions and histograms</h3>
<p><strong>Frequency distributions</strong> report how often each score
was recorded in a given data set. When presented in table form, a
frequency distribution lists all values for a variable along with the
frequency of each.</p>
<p>For example, imagine a researcher obtains the following self-esteem
scores from 16 people (measured as a continuous variable ranging from
0–10):</p>
<p>5 1 3 4 5 6 2 5 5 4 7 4 4 8 6 3</p>
<pre><code>## 
##  DESCRIPTIVES</code></pre>
<p><img src="HPS201_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>The frequency table above helps to summarise the collected data,
allowing us to easily see the number of participants recording each
score. We can also gather from this table the highest concentration of
results towards the centre of the table (those who answered 4 or 5).</p>
<p>The <strong>histogram</strong> is a graphical representation of the
data in the frequency table. A larger data set may be most relevant when
the results are grouped together (known as a <strong>bin</strong>),
while smaller data sets can simply be plotted as collected. Grouping
data in bins assists in reducing the number of ‘random’ results and to
assist in identifying trends.</p>
</div>
<div id="lo9-understand-positive-skew-negative-skew-and-kurtosis"
class="section level3 well">
<h3 class="well">LO9: Understand positive skew, negative skew and
kurtosis</h3>
<p><strong>Bimodal:</strong> A frequency distribution is said to be
bimodal when the majority of results are visible at 2 clear peaks in the
data being presented.</p>
<p><strong>Negatively Skewed:</strong> A greater number of people have
scored at the high end of a scale.</p>
<p><strong>Positively Skewed:</strong> A greater number of people have
scored at the low end of a scale.</p>
<p><strong>Kurtosis:</strong> refers to the peaks of the recorded
variable (<abbr title="low peaked distribution">platykurtosis</abbr> or
<abbr title="high peaked distribution">leptokurtosis</abbr>).</p>
</div>
</div>
<div id="week-2-statistical-notation" class="section level2 well">
<h2 class="well">Week 2: Statistical Notation</h2>
<div id="notation" class="section level3 tabset">
<h3 class="tabset">Notation</h3>
<div id="variables" class="section level4">
<h4>Variables</h4>
<p><span class="math inline">\(\Sigma = sum\)</span></p>
<p><span class="math inline">\(X = variable\)</span></p>
<p><span class="math inline">\(\overline{X} =\)</span> mean of <span
class="math inline">\(X\)</span></p>
</div>
<div id="summation-notation" class="section level4">
<h4>Summation Notation</h4>
<table>
<thead>
<tr class="header">
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">45</td>
</tr>
<tr class="even">
<td align="right">42</td>
</tr>
<tr class="odd">
<td align="right">35</td>
</tr>
<tr class="even">
<td align="right">23</td>
</tr>
<tr class="odd">
<td align="right">52</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\Sigma X = (X_1 + X_2 + X_3 + X_4 + X_5)
=\)</span> 197</p>
<p><span class="math inline">\(\Sigma X^2 = (X_1^2 + X_2^2 + X_3^2 +
X_4^2 + X_5^2) =\)</span> 8247</p>
<p><span class="math inline">\((\Sigma X)^2 = (X_1 + X_2 + X_3 + X_4 +
X_5)^2 =\)</span> 38809</p>
<div class="float">
<img src="~/Documents/BPsychSci/HPS201/Images/Notation.png"
alt="Summation Notation Examples" />
<div class="figcaption">Summation Notation Examples</div>
</div>
</div>
<div id="double-subscripts" class="section level4 unnumbered">
<h4 class="unnumbered">Double Subscripts</h4>
<p><span class="math inline">\(X_{ij}\)</span> where i = the row and j =
the column</p>
<div class="float">
<img src="~/Documents/BPsychSci/HPS201/Images/DoubleNotation.png"
alt="Double Notation Examples" />
<div class="figcaption">Double Notation Examples</div>
</div>
<blockquote>
<p>In the above data set:</p>
<p>3<sup>rd</sup> trial on day 2</p>
<p><span class="math inline">\(X_{2,3} = 13\)</span></p>
<p>4<sup>th</sup> trial on day 1</p>
<p><span class="math inline">\(X_{1,4} = 9\)</span></p>
</blockquote>
</div>
</div>
<div id="measures-of-central-tendency" class="section level3 tabset">
<h3 class="tabset">Measures of Central Tendency</h3>
<p>Once data is collected, research psychologists would usually be
interested in examining the
<abbr title="the mid-point of a frequency distribution">central
tendency</abbr> of this data.</p>
<div id="the-mode" class="section level4">
<h4>The Mode</h4>
<p>The mode is he most frequently occurring value and thus represented
by the highest bar in a histogram.</p>
</div>
<div id="the-median" class="section level4">
<h4>The Median</h4>
<blockquote>
<p>‘the score that corresponds to the point at or below which 50% of the
scores fall when the data are arranged in numerical order’</p>
</blockquote>
<p>A simple rule of thumb formula for finding the <strong>median
location</strong> in a set of scores is <span class="math inline">\((N +
1)/2\)</span> (where <span class="math inline">\(N =\)</span> the number
of scores).</p>
</div>
<div id="the-mean" class="section level4 unnumbered">
<h4 class="unnumbered">The Mean</h4>
<ul>
<li>The most common and popular measure of central tendency is the
mean.</li>
<li>The mean is simply the average score in a data set and is calculated
as:</li>
</ul>
<p><span class="math display">\[\frac{\Sigma X}{N}\]</span></p>
</div>
<div id="relative-pros-cons" class="section level4">
<h4>Relative Pros &amp; Cons</h4>
<table>
<colgroup>
<col width="4%" />
<col width="45%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th><i class="fas fa-ruler fa-lg"></i></th>
<th><i class="fas fa-plus fa-lg"></i></th>
<th><i class="fas fa-minus fa-lg"></i></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mode</td>
<td>- actual value appearing in data</br>- represents the largest number
of people</br>- Unaffected by outliers</td>
<td>- Unable to be manipulated algebraically</br>- Poor indicator of
population trends</td>
</tr>
<tr class="even">
<td>Median</td>
<td>- Unaffected by outliers</td>
<td>- Does not always appear in data</br>- Unable to be manipulated
algebraically</br>- Poor indicator of population trends</td>
</tr>
<tr class="odd">
<td>Mean</td>
<td>- Most common measure</br>- Can be manipulated algebraically</br>-
Good estimate of population mean</td>
<td>- Does not always appear in data</br>- Influenced by outliers</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="variability" class="section level3 tabset">
<h3 class="tabset">Variability</h3>
<div id="range-and-interquartile-range" class="section level4 well">
<h4 class="well">Range and interquartile range</h4>
<ul>
<li><strong>Range</strong> statistics report the minimum and maximum
score in a data set.</li>
<li>The range is influenced by extreme scores.</li>
<li>The range may not provide a true indication of the variability in a
data set if extreme scores are present.</li>
<li>The <strong>interquartile range</strong> overcomes the problem of
extreme values by removing the upper 25% and lower 25% of the
distribution.</li>
<li><strong>Trimmed Samples</strong>: Removing 50% of the data we could
be losing important information.</li>
</ul>
</div>
<div id="average-deviation" class="section level4 well">
<h4 class="well">Average Deviation</h4>
<p>The degree to which scores vary from the mean, when calculating the
mean and then compute how much each score deviates from this average
value. We then average these deviations to provide a single measure of
variability. However, this would not work as some scores will be above,
and some below the mean, resulting in positive and negative deviations
(which will serve to balance each other out and sum to zero)</p>
</div>
<div id="mean-absolute-deviation-m.a.d." class="section level4 well">
<h4 class="well">Mean Absolute Deviation (m.a.d.)</h4>
<p>The mean absolute deviation (m.a.d.) overcomes this problem by using
the absolute values of the deviations. This is helpful as we are not
interested in whether scores are above or below the mean, simply the
extent to which they vary from the mean. The m.a.d. is the sum of the
absolute deviations divided by N to provide an average deviation.</p>
</div>
<div id="variance-s2" class="section level4 well">
<h4 class="well">Variance (<span
class="math inline">\(S^2\)</span>)</h4>
<p>This statistic uses squared deviations to deal with the problem of
positive/negative differences from the mean. A negative value, once
squared, becomes positive. So we calculate the sum of the squared
deviations from the mean (or sums of squares, <span
class="math inline">\(SS\)</span>). This value is then divided by N – 1
to provide the variance:</p>
<p><span class="math display">\[
  S^2 = \frac{\Sigma(X - \overline{X})^2}{N - 1}
\]</span></p>
</div>
<div id="standard-deviation-s" class="section level4 well">
<h4 class="well">Standard Deviation (<span
class="math inline">\(S\)</span>)</h4>
<p>The standard deviation is simply the square root of the variance. It
provides a measure of the average deviation from the mean and is the
most commonly reported statistic of variability. Once the s^2 has been
calculated, it can be converted into the SD by simply taking the square
root of s^2</p>
<p><span class="math display">\[
  S = \sqrt{\frac{\Sigma(X - \overline{X})^2}{N - 1}}
\]</span></p>
</div>
<div id="standard-normal-distribution" class="section level4 well">
<h4 class="well">Standard Normal Distribution</h4>
<p>A variety of statistical techniques assume that the dependent
variables under study are normally distributed in the population. If we
assume a normal distribution then we can make a range of inferences
about the probabilities of particular events or phenomenon.</p>
</div>
<div id="z-scores" class="section level4 well">
<h4 class="well">z-scores</h4>
<p>The standard normal distribution has a mean of 0 and a standard
deviation of 1. We can convert any distribution into a standard normal
distribution by applying the z-score formula, which converts each score
into <strong>standard deviation units.</strong></p>
<p>The formula for z using the IQ test example is:</p>
<p><span class="math display">\[
  z = \frac{X-\overline{X}}{s}
    = \frac{100-130}{15}
    = 2
\]</span></p>
</div>
<div id="using-z-tables" class="section level4 well">
<h4 class="well">Using z tables</h4>
<p>Consider an intelligence test which has a mean of 100 and a standard
deviation of 15 in the general population. From this information we can
work out how much of the area under the normal curve is above 1 standard
deviations from the mean. That is, we can work out the probability of
obtaining a score of 115 or more (+1 standard deviation) on this
intelligence test.</p>
<p>Given that z scores represent standard deviation units we want to
find the area above z = 1. To answer this we need to consult the z
table. From Appendix z you need to find the row corresponding to z = 1
and locate the ‘smaller portion’ column, as we are interested in the
area above that score. You should find that the smaller portion equals
0.1587. So, the probability that a person drawn randomly from the
population will score 115 or above on this intelligence test is 0.1587
or approximately 16%.</p>
</div>
<div id="setting-probable-limits-on-z"
class="section level4 unnumbered">
<h4 class="unnumbered">Setting Probable Limits on z</h4>
<p>Setting limits on an observation provides researchers with a way of
stating the confidence of their results. That is, having set limits on a
score we can specify with a certain degree of confidence that the score
will lie between two values. Usually researchers employ 95% confidence
intervals so that they can say with 95% confidence that a score will lie
between two values. The ztables help us here also. We need to remove 5%
of the area under the curve, which means we need to find the value that
cuts off 2.5% at each end. Inspection of the ztables (Appendix z)
indicates that z = ±1.96 corresponds to this value. This means that we
can be 95% confident that a score on the intelligence test will fall
between 1.96 standard deviations below and 1.96 standard deviations
above the mean. So what does this mean for our intelligence test? This
is simply a matter of calculating scores that correspond to 1.96
standard deviations from the mean. A way to calculate this is provided
by Howell on page 74:</p>
<p><span class="math display">\[
  \begin{aligned}
      X = μ ±1.96\sigma\\
  \end{aligned}
\]</span></p>
<p>where <span class="math inline">\(μ = mean\)</span>, and <span
class="math inline">\(σ = standard\ deviation\)</span>.</p>
<p><span class="math display">\[  \begin{aligned}
      Limits &amp;= 100 \pm 1.96(15)\\
             &amp;= 100 \pm 29.4\\
             &amp;= 70.6\ to\ 129.4\\
  \end{aligned}
\]</span></p>
<p>This indicates that we can be 95% confident that a person selected at
random from the population will score between 70.6 and 129.4 on this
intelligence test. Thus, any score higher than 130 (i.e. 2sd above the
mean) is a rare occurrence as only 2% of the population are expected to
score this highly.</p>
</div>
</div>
</div>
<div id="week-3-sampling-distributions-and-hypothesis-testing"
class="section level2 well">
<h2 class="well">Week 3: Sampling Distributions and Hypothesis
Testing</h2>
<div id="sampling" class="section level3 tabset">
<h3 class="tabset">Sampling</h3>
<div id="sampling-error" class="section level4">
<h4>Sampling Error</h4>
<p>The degree to which the difference between the population mean and
sample mean are “due to chance”, which can be answered using hypothesis
testing and inferential statistics.</p>
</div>
<div id="sampling-distributions" class="section level4 unnumbered">
<h4 class="unnumbered">Sampling Distributions</h4>
<ul>
<li>Identify the degree of variability from one sample to another as a
result of the sampling error.</li>
<li>From an infinite number of samples, with plotted means of these
samples, a normal distribution of means would be the result.</li>
<li>The standard deviation of a sampling mean is known as
<strong>standard error of differences between means</strong>, and shows
the average distance between a sample mean and a population mean.</li>
<li>The standard deviation of a set of means is known as the standard
error.</li>
</ul>
<p>The formula for calculating standard error is:</p>
<p><span class="math display">\[
  \begin{aligned}
    \frac{s}{\sqrt{n}}
  \end{aligned}
\]</span></p>
<p>In summary, here are a few points that can help with your study into
sampling distributions:</p>
<ul>
<li>A random sample should represent the population well so sample
statistics from a random sample should provide reasonable estimates of
the population values.</li>
<li>There is always some error in estimating population values from
sample statistics (sampling error).</li>
<li>If we take repeated samples from a population and calculate the
mean, these mean scores will vary and form a distribution (distribution
of sample means) which will itself have a mean and standard
deviation.</li>
<li>The degree to which the sample means vary from the overall
population mean (i.e. the standard deviation of the sampling
distribution) is the standard error.</li>
<li>Larger samples provide more information than smaller samples so
statistics from large samples have less standard error than statistics
from smaller samples.</li>
</ul>
</div>
</div>
<div id="hypothesis-testing" class="section level3 tabset">
<h3 class="tabset">Hypothesis Testing</h3>
<p>The information provided by the sampling distribution of the mean can
be used to test hypotheses. Hypotheses are specific predictions which
can be subject to an empirical and statistical test. For example,
suppose we wanted to know whether the mean intelligence score of 109 we
have obtained from our sample of 50 people is different from the general
population mean of 100. If our sample was special in some way (e.g. all
high functioning people) we might hypothesise that there would be a
difference. Using the sampling distribution of the mean, we can test
whether such a sample could reasonably have arisen had we drawn our
sample from a population in which μ = 100. That is, what is the
probability of finding a sample which scores 109 on average, given a
population mean of 100? We might find that the probability of obtaining
a score of 109 is 0.20, which is a fairly high probability. Thus, a
sample mean that high is often obtained from a population with a mean of
100—we would conclude there is no statistical difference between our
sample mean and the population mean.</p>
<div id="steps" class="section level4">
<h4>Steps</h4>
<p>The steps that will be used throughout this unit when we are testing
hypotheses using inferential statistics are as follows:</p>
<ol style="list-style-type: decimal">
<li>Begin with a research hypothesis (i.e. that there is a difference in
intelligence between our sample and the population mean; that is, it is
unlikely that our sample comes from a population whose mean is
100).</li>
<li>Set up the null hypothesis (i.e. that there is no difference between
our sample and the population mean; that is, our sample mean comes from
a population whose mean is 100). More to come on the null hypothesis in
the next section!</li>
<li>Construct the sampling distribution of the particular statistic
(depending on the type of statistical technique you are going to use) on
the assumption that the null hypothesis is true.</li>
<li>Conduct the experiment and collect data.</li>
<li>Compare the sample statistic you obtain to the sampling
distribution.</li>
<li>Evaluate the null hypothesis according to the probability of the
statistic. That is, how probable is it that our sample mean comes from a
distribution whose mean is 100? If it is highly unlikely, then we can
reject the null hypothesis and conclude that there is a difference.</li>
</ol>
</div>
<div id="h_0" class="section level4">
<h4><span class="math inline">\(H_0\)</span></h4>
<p>The null hypothesis is the primary starting point for any statistical
test. Basically, the null hypothesis states that there is no difference
between the groups, or that there is no relationship between two or more
variables. In more specific terms and using our intelligence testing
example, it states that the data we have obtained in our sample (mean =
109) are likely to have come from the population with a mean
intelligence score of 100. The subsequent statistical tests that we
employ are used to test the likelihood of this.</p>
<p>Therefore, the probability/likelihood we are referring to is always
the probability of obtaining that particular result given that the null
hypothesis is true (see Howell, p. 90 ‘The first stumbling block’).</p>
<p>You should be familiar with the notation for the null hypothesis. In
this case:</p>
<p><span class="math display">\[
  \begin{aligned}
      H_0: μ = 100
    \end{aligned}
\]</span></p>
<p>This states the null hypothesis (<span
class="math inline">\(H_0\)</span>) that the sample we have drawn comes
from a population with a mean of 100. If it is highly unlikely that the
data we have obtained come from a distribution with a mean of 100 then
we can simply reject the null hypothesis (that there is no difference)
and conclude that there is a difference between our sample mean and that
of the population.</p>
<p>What happens if our data do not lead us to reject the null
hypothesis? That is, often the statistics tell us that our sample mean
is no different from the population (e.g. the difference could be just
due to chance). Thus, the null hypothesis is ‘proved’ or ‘supported’. In
these cases it is best to say that we fail to reject the null
hypothesis. In summary, the null hypothesis states that there is no
difference between groups, or no relationship between variables
(i.e. null effect). The statistical test evaluates the likelihood of
obtaining the data we have (e.g. mean of 109 on intelligence) if we took
this sample from a population with a mean of 100.</p>
</div>
<div id="hypothesis-testing-using-the-normal-distribution"
class="section level4">
<h4>Hypothesis Testing using the Normal Distribution</h4>
<p>The following example is similar to the one provided by Howell. The
principles are the same; however, illustrating the technique with a
slightly different data set and outcome will be helpful in consolidating
your understanding.</p>
<p>Research psychologists specialising in cognitive processes often
study attention and the influence of attentional biases on a range of
behaviours. One such behaviour is drug and alcohol use. Evidence shows
that dependent drinkers allocate a large amount of their attention
toward stimuli associated with drinking (e.g. pictures of alcohol,
alcohol advertisements).</p>
<p>A computerised test of this has been developed which assesses the
number of milliseconds a person takes to respond to the colour of words
that are associated with alcohol represented on screen. Theoretically,
the longer it takes them to name the colour of the word, the more
attention is being drawn to the word itself. Researchers know that in
the normal population, response times are normally distributed with a
mean of 900 milliseconds and a standard deviation of 120
milliseconds.</p>
<p>Suppose an individual is referred to a cognitive psychologist with a
score of 1100 milliseconds. Is this score sufficiently longer than the
mean population response time to assume that this person did not come
from a population of ‘normal’ people?</p>
<p>Here is the distribution of scores (sample means) on this task in the
normal population (<span class="math inline">\(\mu = 900, \sigma =
120\)</span>). The sample score we have obtained is also indicated under
the distribution.</p>
<p>The first step here is to state the null hypothesis:</p>
<p><span class="math inline">\(H_0\)</span>: There is no difference
between our sample mean and the population mean. That is, the
individual’s score does come from the population of ‘normal’ attention
scores.</p>
<p>Next we can calculate the probability of scoring 1100 given a normal
population mean of 900 (standard deviation of 120). That is, we can now
calculate the probability that a score as high as this would be obtained
from this population. All we need to do is calculate the z score for
this observed value and determine the probability using the normal
distribution table (or z tables, as we did in Topic 2).</p>
<p><span class="math display">\[
  \begin{aligned}
    z &amp;= \frac{X - \mu}{\sigma}\\
    &amp;= \frac{1100 - 900}{120}\\
    &amp;= 1.67
  \end{aligned}
\]</span></p>
<p>Thus, we have a z score of 1.67. If we consult the z tables (Appendix
z in Howell) we will see that the probability of a z score of 1.67 or
above is 0.0475. The smaller portion column in the z table tells us the
proportion of the population that score at that point and above.
Therefore, less than 5% of the population score 1100 milliseconds or
longer on this task. Statistically speaking, the probability that this
score comes from a population with a mean of 900 is less than 5%. Is
this likelihood sufficiently small? How do we decide if we can reject
the null hypothesis based on this information?</p>
</div>
<div id="decision-making" class="section level4 unnumbered">
<h4 class="unnumbered">Decision Making</h4>
<p>To answer this question, we need to compare our obtained probability
value to some standard. The conventional approach to this is to use the
0.05 level as a ‘cut off’. This is referred to as the rejection or
significance level of the statistical test. If our probability level is
less than or equal to this ‘rejection level’ then we reject H0. As noted
by Howell, this is an arbitrary convention that has been established
over the years for specific reasons but one that is pervasive throughout
psychological research. Other significance levels are used (e.g. 0.01)
for a variety of reasons. At this stage it is only necessary for you to
know that the standard level of significance/rejection is 0.05.</p>
<p>The probability level we have obtained in the example is p = 0.0475.
This is less than 0.05 and therefore, following the decision rule, we
can reject the null hypothesis. Thus, we can say that it is highly
unlikely that the person came from the ‘normal population’ and conclude
that the score of 1100 is sufficiently different from the normal
population mean.</p>
<p>In this case, we have supported the alternative hypothesis, which
states that there is a difference between the sample mean and the
population mean. This is in essence, the opposite to the null
hypothesis:</p>
<p>As you know, the null hypothesis is that of no difference:</p>
<p><span class="math display">\[
  \begin{aligned}
    H_0: \mu = 900
  \end{aligned}
\]</span></p>
<p>The alternative hypothesis is that there is a difference:</p>
<p><span class="math display">\[
  \begin{aligned}
    H_1: \mu \ne 900
  \end{aligned}
\]</span></p>
<p>Or, that the mean is higher than or lower than the population
mean:</p>
<p><span class="math display">\[
  \begin{aligned}
    H_1: \mu \gt 900\\
    H_1: \mu \lt 900
  \end{aligned}
\]</span></p>
</div>
</div>
<div id="type-i-and-ii-errors" class="section level3 well">
<h3 class="well">Type I and II errors</h3>
<p>There is always some error associated with decision making in
everyday life. However, as noted by Howell, in statistics we can
precisely identify the probability of making an error in our decision
making processes.</p>
<p>For example, above we rejected the null hypothesis and concluded that
the person did not come from the ‘normal’ population. That is, the
probability of obtaining a score of 1100 milliseconds was sufficiently
small (i.e. less than 0.05) as to be unlikely to have come from the
‘normal’ population.</p>
<p>However the fact that we are using the 0.05 ‘rejection’ level as our
cut off produces a degree of error: a 5% degree of error to be
exact.</p>
<p>A <strong>Type I</strong> error is when we erroneously reject a null
hypothesis. It is the probability of rejecting a ‘true’ null hypothesis
(e.g. the probability of saying there is a difference when there in fact
isn’t). The risk of a Type I error is small and under the control of the
researcher (it can be set at 0.01, for example).</p>
<p>A <strong>Type II</strong> errors occurs when we fail to reject a
false null hypothesis. So whenever we fail to reject a null hypothesis
there is a risk of a Type II error. This relates to the power of the
test the probability of rejecting a null hypothesis when it is
false.</p>
<p>The difference between Type I and Type II errors are illustrated in
the table below for quick reference (see also Howell, p. 98).</p>
<table>
<thead>
<tr class="header">
<th align="center">Decision</th>
<th align="center"><span class="math inline">\(H_0\)</span>: True</th>
<th align="center"><span class="math inline">\(H_0\)</span>: False</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Reject <span class="math inline">\(H_0\)</span></td>
<td align="center">Type I error</td>
<td align="center">Correct decision</td>
</tr>
<tr class="even">
<td align="center">Don’t reject <span
class="math inline">\(H_0\)</span></td>
<td align="center">Correct decision</td>
<td align="center">Type II error</td>
</tr>
</tbody>
</table>
</div>
<div id="one-and-two-tailed-tests" class="section level3 well">
<h3 class="well">One and Two Tailed Tests</h3>
<p>One-tailed test: <span class="math inline">\(\lt\)</span> or <span
class="math inline">\(\gt\)</span> (directional). For a one-tailed test,
we use the full 5% rejection region in the ‘one-tail’, in this example
the high tail. Thus, any scores that fall in the top 5% of scores are
considered sufficiently unlikely.</p>
<blockquote>
<p>One-tailed test: <span class="math inline">\(H_1: \mu \gt
900\)</span></p>
</blockquote>
<p>Two-tailed test: <span class="math inline">\(\ne\)</span>
(measuring/comparing difference). For a two-tailed test we must separate
the proportion into the two tails: 0.025 at one end, 0.025 at the other
(so that the overall probability level is set at 0.05).</p>
<blockquote>
<p>Two-tailed test: <span class="math inline">\(H_1: \mu \ne
900\)</span></p>
</blockquote>
</div>
</div>
<div id="week-4-chi-square" class="section level2 well">
<h2 class="well">Week 4: Chi-Square</h2>
<div id="goodness-of-fit" class="section level3 well">
<h3 class="well">Goodness of Fit</h3>
<ul>
<li>Used for a <strong>single</strong> categorical (discrete)
variable</li>
<li>Used to determine percentages (proportions)</li>
<li>Used for data about frequencies of responses</li>
</ul>
<p><span class="math inline">\(O\)</span> = Observed Frequencies</p>
<p><span class="math inline">\(E\)</span> = Expected Frequencies</p>
<div id="formula" class="section level4">
<h4>Formula</h4>
<p><span class="math inline">\(\chi^2 =
\Sigma{\frac{(O-E)^2}{E}}\)</span></p>
</div>
<div id="steps-1" class="section level4">
<h4>Steps:</h4>
<ol style="list-style-type: decimal">
<li>Calculate the difference between Observed and Expected
frequencies</li>
<li>Square the deviation score</li>
<li>Divide by the expected frequency</li>
<li>Sum the resulting values</li>
<li>Compare the results to the critical value (from the chi-square
table)</li>
</ol>
</div>
<div id="lemonade-preferences-between-males-and-females"
class="section level4">
<h4>Lemonade Preferences between males and females</h4>
<table class="table table-hover">
<tr scope="row">
<th scope="col">
</th>
<th scope="col">
A
</th>
<th scope="col">
B
</th>
<th scope="col">
C
</th>
</tr>
<tr scope="row">
<td>
Observed
</td>
<td>
5
</td>
<td>
18
</td>
<td>
7
</td>
</tr>
<tr scope="row">
<td>
Expected
</td>
<td>
10
</td>
<td>
10
</td>
<td>
10
</td>
</tr>
</table>
<div id="chi-square-value" class="section level5">
<h5>Chi-square Value</h5>
<p><span class="math inline">\(\chi^2 =
\overbrace{\frac{(5-10)^2}{10}}^{A} +
\overbrace{\frac{(18-10)^2}{10}}^{B} +
\overbrace{\frac{(7-10)^2}{10}}^{C}\)</span></p>
<p><span class="math inline">\(= \frac{25}{10} + \frac{64}{10} +
\frac{9}{10}\)</span></p>
<p><span class="math inline">\(= 9.8\)</span></p>
</div>
<div id="degrees-of-freedom" class="section level5">
<h5>Degrees of Freedom</h5>
<p><span class="math inline">\(df = C-1\)</span></p>
</div>
<div id="critical-chi-square-value-from-chi-table"
class="section level5">
<h5>Critical Chi-square Value (from Chi Table)</h5>
<p><span class="math inline">\(5.99(df=2, \alpha = .05)\)</span></p>
<p><span class="math inline">\(\chi^2 = 9.8\)</span> which is greater
than critical value.</p>
</div>
<div id="decision-making-1" class="section level5">
<h5>Decision Making</h5>
<ul>
<li>If our calculated <span class="math inline">\(\chi^2\)</span> value
is grater than our critical <span class="math inline">\(\chi^2\)</span>
value, we reject the null hypothesis</li>
<li>Rejection of the null hypothesis confirms that our Observed values
significantly differ from our Expected values (as a result of chance)
### Independence Test {.well}</li>
</ul>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed
diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit
amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel
scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet
fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor
ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla
sed consectetur.</p>
</div>
</div>
</div>
</div>
<div id="week-5-t-tests" class="section level2 well">
<h2 class="well">Week 5: t-tests</h2>
<p><strong>3 main types:</strong></p>
<ul>
<li>One Sample: compares a single sample mean to a known population
mean</li>
<li>Matched Samples: Compares changes in a sample mean across time</li>
<li>Independent Samples: Compares two different sample means</li>
</ul>
<div id="overview-of-the-t-test" class="section level3">
<h3>Overview of the t-test</h3>
<ul>
<li>Used for comparing the means of continuous (measurement) data (IQ,
height, exam results)</li>
<li>Differences between sample means</li>
<li>Estimates the Standard Error (difference we expect to see by chance)
using sample statistics</li>
<li>t-statistic is a ratio of the mean differences obtained and the mean
differences expected by chance</li>
</ul>
<p><span class="math display">\[
  t = \frac{obtained\ mean\ difference}{std\ diff\ expected\ by\ chance}
\]</span></p>
</div>
<div id="standard-error" class="section level3">
<h3>Standard Error</h3>
<ul>
<li>The extent to which sample means deviate from the population
mean</li>
<li>The difference between the population mean and the sample mean we
should expect by chance.</li>
</ul>
<p>Standard error is estimated using the <em>Central Limit
Theorem</em>:</p>
<p><span class="math display">\[
  = \frac{\sigma}{\sqrt{n}} = \frac{pop&#39;n\ sd}{\sqrt{sample\ size}}
\]</span></p>
</div>
<div id="comparing-the-sample-mean-to-population-mean"
class="section level3">
<h3>Comparing the sample mean to population mean</h3>
<p><span class="math display">\[
  z = \frac{\overline{X} - \mu}{\frac{\sigma}{\sqrt{n}}}
\]</span></p>
<p><em>This theorem confirms that the larger the sample size, the lower
the error</em></p>
</div>
<div id="one-sample-t-test" class="section level3 well">
<h3 class="well">One Sample t-test</h3>
<p>Compares a single sample mean to a population mean (when we do not
know <span class="math inline">\(\sigma\)</span>)</p>
<div id="example-1" class="section level4">
<h4>Example</h4>
<ul>
<li>‘Impulsiveness’ questionnaire (continuous scale from 0 - 18)</li>
<li><span class="math inline">\(\mu = 7.01\)</span></li>
<li>Sample of 10 drug users (<span class="math inline">\(n =
10\)</span>)</li>
<li>Higher levels of impulsiveness is expected in drug users compared to
the rest of the population.</li>
</ul>
</div>
<div id="hypotheses" class="section level4">
<h4>Hypotheses</h4>
<p><span class="math display">\[\begin{align}
  H_0: \mu = 7.01 \\
  H_a: \mu \ne 7.01 \\
\end{align}\]</span></p>
</div>
<div id="sample-data" class="section level4">
<h4>Sample Data</h4>
<table class="table table-hover">
<thead>
<tr scope="row">
<th scope="col">
<span class="math inline">\(X\)</span>
</th>
<th scope="col">
<span class="math inline">\(X-\overline{X}\)</span>
</th>
<th scope="col">
<span class="math inline">\((X-\overline{X})^2\)</span>
</th>
</tr>
</thead>
<tbody>
<tr scope="row">
<td>
8.5
</td>
<td>
-1.37
</td>
<td>
1.88
</td>
</tr>
<tr scope="row">
<td>
12.1
</td>
<td>
2.23
</td>
<td>
4.97
</td>
</tr>
<tr scope="row">
<td>
10
</td>
<td>
0.13
</td>
<td>
0.02
</td>
</tr>
<tr scope="row">
<td>
5.2
</td>
<td>
-4.67
</td>
<td>
21.81
</td>
</tr>
<tr scope="row">
<td>
15.3
</td>
<td>
5.43
</td>
<td>
29.48
</td>
</tr>
<tr scope="row">
<td>
6.2
</td>
<td>
-3.67
</td>
<td>
13.47
</td>
</tr>
<tr scope="row">
<td>
9.1
</td>
<td>
-0.77
</td>
<td>
0.59
</td>
</tr>
<tr scope="row">
<td>
10.2
</td>
<td>
0.33
</td>
<td>
0.11
</td>
</tr>
<tr scope="row">
<td>
7.9
</td>
<td>
-1.97
</td>
<td>
3.88
</td>
</tr>
<tr scope="row">
<td>
14.2
</td>
<td>
4.33
</td>
<td>
18.75
</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\begin{align}
  \overline{X} = ???
  s &amp;= \sqrt{\frac{\Sigma(X-\overline{X})^2}{n-1}} =
\sqrt{\frac{95}{9}} = 3.25 \\
  t &amp;= \frac{\overline{X} - \mu}{\frac{s}{\sqrt{n}}} = \frac{9.87 -
7.01}{\frac{3.25}{\sqrt{10}}} = \frac{2.86}{1.03} \\
  &amp;= 2.78(df = 9)
\end{align}\]</span></p>
</div>
<div id="decision-making-2" class="section level4">
<h4>Decision Making</h4>
<ul>
<li>Calculated t-value = 2.78</li>
<li>Critical (from table) t-value = 2.262</li>
<li>Since the calculated t-value is greater than the
<abbr title="from a table">critical</abbr> t-value, we can reject the
null hypothesis. The drug users in this sample showed significantly
higher levels of impulsivity than the general population.</li>
</ul>
<p><img src="images/OneSampleT.png" style="width:50.0%" /></p>
<blockquote>
<h4 id="reporting"><strong>Reporting</strong></h4>
<p>‘The drug users in this sample reported significantly higher levels
of impulsivity compared to the general population, <em>t</em>(9) = 2.78,
<em>p</em> &lt; .05.’</p>
</blockquote>
</div>
</div>
<div id="matched-samples-t-test" class="section level3 well">
<h3 class="well">Matched Samples t-test</h3>
<ul>
<li>Also known as related samples, repeated measures, dependent
samples</li>
<li>Same participants with measures recorded on two occasions (e.g. Pre
and Post treatment)</li>
<li>Scores are matched from one point in time to the next</li>
<li>Examine the change in means from time<sub>1</sub> to
time<sub>2</sub></li>
</ul>
<p><img src="Images/matchSample.png" style="width:50.0%" /></p>
<p><strong>A matched samples t-test tells us whether the change in mean
scores is statistically significant</strong></p>
<div id="steps-2" class="section level4">
<h4>Steps:</h4>
<ol style="list-style-type: decimal">
<li>Obtain scores before and after treatment</li>
<li>Calculate difference scores before and after treatment</li>
<li>Calculate mean and standard deviation of the difference of
scores</li>
<li>Calculate matched samples t-test</li>
</ol>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Before
</th>
<th style="text-align:right;">
After
</th>
<th style="text-align:right;">
Difference
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9.6
</td>
<td style="text-align:right;">
7.1
</td>
<td style="text-align:right;">
2.5
</td>
</tr>
<tr>
<td style="text-align:right;">
10.5
</td>
<td style="text-align:right;">
7.6
</td>
<td style="text-align:right;">
2.9
</td>
</tr>
<tr>
<td style="text-align:right;">
12.4
</td>
<td style="text-align:right;">
8.2
</td>
<td style="text-align:right;">
4.2
</td>
</tr>
<tr>
<td style="text-align:right;">
8.7
</td>
<td style="text-align:right;">
7.7
</td>
<td style="text-align:right;">
1.0
</td>
</tr>
<tr>
<td style="text-align:right;">
8.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
2.0
</td>
</tr>
<tr>
<td style="text-align:right;">
11.2
</td>
<td style="text-align:right;">
8.2
</td>
<td style="text-align:right;">
3.0
</td>
</tr>
<tr>
<td style="text-align:right;">
15.1
</td>
<td style="text-align:right;">
9.7
</td>
<td style="text-align:right;">
5.4
</td>
</tr>
<tr>
<td style="text-align:right;">
9.4
</td>
<td style="text-align:right;">
8.3
</td>
<td style="text-align:right;">
1.1
</td>
</tr>
<tr>
<td style="text-align:right;">
14.3
</td>
<td style="text-align:right;">
13.2
</td>
<td style="text-align:right;">
1.1
</td>
</tr>
<tr>
<td style="text-align:right;">
12.1
</td>
<td style="text-align:right;">
8.4
</td>
<td style="text-align:right;">
3.7
</td>
</tr>
<tr>
<td style="text-align:right;">
13.7
</td>
<td style="text-align:right;">
9.3
</td>
<td style="text-align:right;">
4.4
</td>
</tr>
<tr>
<td style="text-align:right;">
10.2
</td>
<td style="text-align:right;">
7.0
</td>
<td style="text-align:right;">
3.2
</td>
</tr>
<tr>
<td style="text-align:right;">
13.8
</td>
<td style="text-align:right;">
8.8
</td>
<td style="text-align:right;">
5.0
</td>
</tr>
<tr>
<td style="text-align:right;">
8.9
</td>
<td style="text-align:right;">
6.9
</td>
<td style="text-align:right;">
2.0
</td>
</tr>
<tr>
<td style="text-align:right;">
14.5
</td>
<td style="text-align:right;">
8.1
</td>
<td style="text-align:right;">
6.4
</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\begin{align}
  \overline{D} &amp;= 3.19 \\
  s &amp;= \sqrt{\frac{\Sigma (D-\overline{D})^2}{n-1}} =
\sqrt{\frac{38.17}{14}} =  1.65 \\
  t &amp;= \frac{\overline{D} - 0}{\frac{s}{\sqrt{n}}} = \frac{3.19 -
0}{\frac{1.65}{\sqrt{15}}} = \frac{3.19}{0.42} \\
  &amp;= 7.59(df = 14)
\end{align}\]</span></p>
</div>
<div id="decision-making-3" class="section level4">
<h4>Decision Making</h4>
<ul>
<li>Calculated t-value = 7.59</li>
<li>Critical (from table) t-value = 2.145 (two-sided)</li>
<li>Since the calculated t-value is greater than the
<abbr title="from a table">critical</abbr> t-value, we can reject the
null hypothesis. The changes in impulsiveness over time were
significant.</li>
</ul>
</div>
<div id="effect-size" class="section level4">
<h4>Effect Size</h4>
<p>Represented by Cohen’s <em>d</em>, and reports the difference in
standard deviation units. (0.20 = small, 0.50 = moderate, 0.8+ =
large)</p>
<p><span class="math display">\[\begin{align}
  \overline{X_1} &amp;= 11.53 \\
  \overline{X_2} &amp;= 8.33 \\
  d &amp;= \frac{\overline{X}_1 - \overline{X}_2}{s_{X1}} = \frac{11.53
- 8.33}{2.32} = 1.38 \\
\end{align}\]</span></p>
<blockquote>
<h4 id="reporting-1">Reporting</h4>
<h5 id="matched-sample-t-test"><strong>Matched Sample
t-test</strong></h5>
<p>‘Overall the sample were significantly less impulsive following the
treatment program (<em>M</em> = 8.33, <em>SD</em> = 1.61) than they were
before it (<em>M</em> = 11.53, <em>SD</em> = 2.32), <em>t</em>(14) =
7.59, <em>p</em> &lt; .05.’</p>
<h5 id="effect-size-1"><strong>Effect Size</strong></h5>
<p>‘Impulsivity has reduced by almost 1.5 SD of pre-treatment
levels’</p>
</blockquote>
</div>
</div>
<div id="independent-samples-t-test-equal-sample-sizes"
class="section level3 well">
<h3 class="well">Independent Samples t-test (equal sample sizes)</h3>
<p>Compares the sample means of two independent groups where DVs are
continuous and population means are unknown.</p>
<p><img src="Images/indSamples2.png" style="width:50.0%" /></p>
<div id="hypotheses-1" class="section level4">
<h4>Hypotheses</h4>
<p><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> OR <span
class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span></p>
<p><span class="math inline">\(H_1: \mu_1 \ne \mu_2\)</span> OR <span
class="math inline">\(H_0: \mu_1 - \mu_2 \ne 0\)</span></p>
</div>
<div id="differences-between-sample-means" class="section level4">
<h4>Differences between Sample Means</h4>
<ul>
<li>Investigates the differences between (and Standard Error of) sample
means.</li>
<li>Used when sample sizes are equal.</li>
<li>Two groups: smokers (<span class="math inline">\(n=10\)</span>), and
non-smokers (<span class="math inline">\(n=10\)</span>)</li>
<li>The DV is mean anxiety scores (on a scale of 0 - 20)</li>
<li>smokers (<span class="math inline">\(\overline{X}=15.31\)</span>,
<span class="math inline">\(s=4.42\)</span>)</li>
<li>non-smokers (<span
class="math inline">\(\overline{X}=12.19\)</span>, <span
class="math inline">\(s=3.28\)</span>)</li>
</ul>
<p><span class="math display">\[\begin{align}
  t &amp;= \frac{\overline{X}_1-\overline{X}_2}{\sqrt{\frac{s^2_1}{n_1}
+ \frac{s^2_2}{n_2}}}
=         \frac{15.31-12.19}{\sqrt{\frac{19.54}{10} + \frac{10.76}{10}}}
= \frac{3.12}{\sqrt{1.95+1.08}} = \frac{3.12}{1.74} = 1.79 \\
  df &amp;= (n_1-1)+(n_2-1)=(10-1)+(10-1)=18 \\
\end{align}\]</span></p>
<blockquote>
<p><span class="math inline">\(t(18) = 1.79,\ p&gt;.05,\ two\
tailed\)</span></p>
</blockquote>
</div>
<div id="decision-making-4" class="section level4">
<h4>Decision Making</h4>
<ul>
<li>Calculated t-value = 1.79</li>
<li>Critical (from table) t-value = 2.1 (two-sided)</li>
<li>The calculated <span class="math inline">\(t\)</span>-value of 1.79
is less than our <abbr title="from a table">critical</abbr> t-value of
2.1, which falls within our 95% confidence interval, meaning that the
result is not statistically significant enough for us to reject the null
hypothesis.</li>
</ul>
</div>
</div>
<div id="independent-samples-t-test-unequal-sample-sizes"
class="section level3 well">
<h3 class="well">Independent Samples t-test (unequal sample sizes)</h3>
<div id="pooled-variance" class="section level4">
<h4>Pooled Variance</h4>
<p>The variance of our sample sizes is averaged using the following
formula:</p>
<p><span class="math display">\[\begin{align}
  s^2_p = \frac{(n_1 - 1)s^2_1 + (n_2 - 1)s^2_2}{n_1 + n_2 - 2}
\end{align}\]</span></p>
<p>Our t-statistic formula then becomes:</p>
<p><span class="math display">\[\begin{align}
  t = \frac{(\overline{X}_1 - \overline{X}_2)}{\sqrt{\frac{s^2_p}{n_1} +
\frac{s^2_p}{n_2}}}
\end{align}\]</span></p>
</div>
<div id="example-2" class="section level4">
<h4>Example</h4>
<ul>
<li>Two groups: smokers (<span class="math inline">\(n=12\)</span>) and
non-smokers (<span class="math inline">\(n=27\)</span>)</li>
<li>Our DV is mean anxiety scores (on a scale of 0 - 20)</li>
<li>Smokers (<span class="math inline">\(\overline{X} = 15.31\)</span>,
<span class="math inline">\(s=4.42\)</span>)</li>
<li>Non-Smokers (<span class="math inline">\(\overline{X} =
12.19\)</span>, <span class="math inline">\(s=3.28\)</span>)</li>
</ul>
<div id="pooled-variance-1" class="section level5">
<h5>Pooled Variance</h5>
<p><span class="math display">\[\begin{align}
  s^2_p &amp;= \frac{(n_1 - 1)s^2_1 + (n_2 - 1)s^2_2}{n_1 + n_2 - 2} \\
  &amp;= \frac{(12 - 1)4.42^2 + (27 - 1)3.28^2}{12 + 27 - 2} \\
  &amp;= \frac{(11 \times 19.54) + (26 \times 10.76)}{37} \\
  &amp;= \frac{214.94 + 279.76}{37} = \frac{494.70}{37} = 13.37
\end{align}\]</span></p>
</div>
<div id="t-test" class="section level5">
<h5>t-test</h5>
<p><span class="math display">\[\begin{align}
  t &amp;= \frac{(\overline{X}_1 -
\overline{X}_2)}{\sqrt{\frac{s^2_p}{n_1} + \frac{s^2_p}{n_2}}} \\
  &amp;= \frac{(15.31 - 12.19)}{\sqrt{\frac{13.37}{12} +
\frac{13.37}{27}}} \\
  &amp;= \frac{3.12}{\sqrt{\frac{1.11}{0.50} + \frac{13.37}{27}}} =
\frac{3.12}{\sqrt{1.11 + 0.50}} = \frac{3.12}{1.27} = 2.45
\end{align}\]</span></p>
<blockquote>
<p><span class="math inline">\(t(37) = 2.45\)</span>, <span
class="math inline">\(p&lt;.05\)</span></p>
</blockquote>
</div>
</div>
<div id="decision-making-5" class="section level4">
<h4>Decision Making</h4>
<ul>
<li>Calculated t-value = 2.45</li>
<li><abbr title="from a table">Critical</abbr> = 2.026 (two-sided)</li>
<li>The calculated <span class="math inline">\(t\)</span>-value of 2.45
is greater than our <abbr title="from a table">critical</abbr> t-value
of 2.026, meaning that the result is statistically significant enough
for us to reject the null hypothesis.</li>
</ul>
<blockquote>
<h4 id="reporting-2">Reporting</h4>
<p>‘Overall there is a significant difference in anxiety levels between
smokers (<em>M</em> = 15.31, <em>SD</em> = 4.42) and non-smokers
(<em>M</em> = 12.19, <em>SD</em> = 3.28), <em>t</em>(37) = 2.45,
<em>p</em> &lt; .05.’</p>
</blockquote>
</div>
</div>
<div id="confidence-limits" class="section level3 well">
<h3 class="well">Confidence limits</h3>
<ul>
<li>Confidence limits (or confidence interval) provide a range of
possible values existing within our 95% confidence level.</li>
<li>Becoming more and more important in psychological research as it
gives researchers an idea of how meaningful the difference is.</li>
<li><strong>If the interval does not include zero our rejection of the
null hypothesis is correct.</strong></li>
<li>Confidence limits are calculated very simply as:
<ul>
<li>The <span class="math inline">\(\overline{D} \pm t_{crit}\)</span>
(standard error of the mean difference)</li>
</ul></li>
</ul>
<p>As in the above example:</p>
<p><span class="math display">\[\begin{align}
  CI &amp;= \overline{D} \pm z\frac{s}{\sqrt{n}} \\
  &amp;= 3.12 \pm z\frac{s}{\sqrt{n}} \\
  &amp;= 3.12 ± 2.026(1.27) \\
  &amp;= 3.12 ± 2.573 \\
  &amp;= 0.547\ to\ 5.693
\end{align}\]</span></p>
<p><em>As mentioned above, this interval does not contain zero, so we
can be reassured that our rejection of the null hypothesis is
correct.</em></p>
</div>
</div>
<div id="week-6-correlation" class="section level2 well">
<h2 class="well">Week 6: Correlation</h2>
<div id="introduction" class="section level3 well">
<h3 class="well">Introduction</h3>
<p>The purpose of correlation and regression is to describe the
relationship between two variables:</p>
<ul>
<li>Correlation is the simple form of this where two variables are
assessed for the degree and direction of their relationship.</li>
<li>Regression is an extension of correlation allowing for the
prediction of one variable based on the scores from another.</li>
<li>The variable on the X and Y dimensions are also referred to as the
predictor and the criterion variable respectively.</li>
<li>A scatterplot also highlights 3 dimensions:
<ul>
<li>Type (linear, non-linear)</li>
<li>Strength (strong, weak) is conveyed as a measure between -1 and
1</li>
<li>Direction (positive, negative)</li>
</ul></li>
</ul>
<div id="scatterplots" class="section level4">
<h4>Scatterplots</h4>
<table class="table table-hover">
<thead>
<tr scope="row">
<th scope="col">
Person
</th>
<th scope="col">
Anxiety (X)
</th>
<th scope="col">
Negative mood (Y)
</th>
</tr>
</thead>
<tbody>
<tr scope="row">
<td>
A
</td>
<td>
5
</td>
<td>
4
</td>
</tr>
<tr scope="row">
<td>
B
</td>
<td>
8
</td>
<td>
6
</td>
</tr>
<tr scope="row">
<td>
C
</td>
<td>
9
</td>
<td>
5
</td>
</tr>
<tr scope="row">
<td>
D
</td>
<td>
2
</td>
<td>
1
</td>
</tr>
<tr scope="row">
<td>
E
</td>
<td>
7
</td>
<td>
5
</td>
</tr>
<tr scope="row">
<td>
F
</td>
<td>
4
</td>
<td>
3
</td>
</tr>
<tr scope="row">
<td>
G
</td>
<td>
9
</td>
<td>
7
</td>
</tr>
<tr scope="row">
<td>
H
</td>
<td>
6
</td>
<td>
7
</td>
</tr>
<tr scope="row">
<td>
I
</td>
<td>
1
</td>
<td>
4
</td>
</tr>
<tr scope="row">
<td>
J
</td>
<td>
8
</td>
<td>
7
</td>
</tr>
</tbody>
</table>
<p><img src="Images/Wk6Ex1.png" style="width:35.0%"
alt="Positive Correlation" /> <img src="Images/Wk6Ex2.png"
style="width:35.0%" alt="Negative Correlation" /></p>
</div>
<div id="regression-lines" class="section level4">
<h4>Regression Lines</h4>
<ul>
<li><abbr title="Lines of best fit">Regression lines</abbr> are used in
prediction to obtain an estimate of either the corresponding X or Y
value.</li>
<li>A specific formula is used to calculate the exact values.</li>
<li>This illustration of regression highlights the difference between
the predictor variable and the criterion variable. When we conduct a
regression analysis we would normally have a research question which
asks the extent to which one variable (the predictor, X) is able to
predict scores on another (the criterion, Y). To reflect this, the
predictor variable is usually placed on the X axis, and the criterion is
placed on the Y axis.</li>
</ul>
</div>
<div id="pearsons-correlation-coefficient-r" class="section level4">
<h4>Pearson’s Correlation Coefficient (r)</h4>
<p><span class="math display">\[\begin{align}
  r = \frac{cov_{xy}}{s_xs_y} = \frac{covariance}{sd\ x\ and\ y} \\
\end{align}\]</span></p>
</div>
<div id="covariance" class="section level4">
<h4>Covariance</h4>
<p><span class="math display">\[\begin{align}
  cov_{xy} = \frac{\Sigma(X-\overline{X})(Y-\overline{Y})}{N-1} \\
\end{align}\]</span></p>
<p>This formula is essentially the sum of the deviation products divided
by N – 1.</p>
</div>
</div>
<div id="example-3" class="section level3 well">
<h3 class="well">Example</h3>
<ul>
<li>Ten participants completed questionnaires which measured trait
anxiety and negative mood.</li>
<li>The researcher was interested in examining whether a highly
trait-anxious person is more likely to report more negative mood
throughout the course of a day.</li>
<li>Higher scores on both measures indicate higher trait anxiety and
more negative mood.</li>
</ul>
<table class="table table-hover">
<thead>
<tr scope="row">
<th scope="col" colspan="2">
Scores
</th>
<th scope="col" colspan="2">
Deviations<BR>from mean
</th>
<th scope="col">
Products
</th>
</tr>
<tr scope="row">
<th scope="col">
Anxiety(X)
</th>
<th scope="col">
Negative<BR>mood (Y)
</th>
<th scope="col">
<span class="math inline">\(X - \overline{X}\)</span>
</th>
<th scope="col">
<span class="math inline">\(Y - \overline{Y}\)</span>
</th>
<th scope="col">
<span class="math inline">\((X-\overline{X})(Y-\overline{Y})\)</span>
</th>
</tr>
</thead>
<tbody>
<tr scope="row">
<td>
5
</td>
<td>
4
</td>
<td>
–0.9
</td>
<td>
–0.9
</td>
<td>
0.81
</td>
</tr>
<tr scope="row">
<td>
8
</td>
<td>
6
</td>
<td>
2.1
</td>
<td>
1.1
</td>
<td>
2.31
</td>
</tr>
<tr scope="row">
<td>
9
</td>
<td>
5
</td>
<td>
3.1
</td>
<td>
0.1
</td>
<td>
0.31
</td>
</tr>
<tr scope="row">
<td>
2
</td>
<td>
1
</td>
<td>
–3.9
</td>
<td>
–3.9
</td>
<td>
15.21
</td>
</tr>
<tr scope="row">
<td>
7
</td>
<td>
5
</td>
<td>
1.1
</td>
<td>
0.1
</td>
<td>
0.11
</td>
</tr>
<tr scope="row">
<td>
4
</td>
<td>
3
</td>
<td>
–1.9
</td>
<td>
–1.9
</td>
<td>
3.61
</td>
</tr>
<tr scope="row">
<td>
9
</td>
<td>
7
</td>
<td>
3.1
</td>
<td>
2.1
</td>
<td>
6.51
</td>
</tr>
<tr scope="row">
<td>
6
</td>
<td>
7
</td>
<td>
0.1
</td>
<td>
2.1
</td>
<td>
0.21
</td>
</tr>
</tbody>
</table>
<table class="table table-hover">
<thead>
<tr scope="row">
<th scope="col">
Measure
</th>
<th scope="col">
Value
</th>
</tr>
</thead>
<tbody>
<tr scope="row">
<td>
<span class="math inline">\(\overline{X}\)</span>
</td>
<td>
5.9
</td>
</tr>
<tr scope="row">
<td>
<span class="math inline">\(\overline{Y}\)</span>
</td>
<td>
4.9
</td>
</tr>
<tr scope="row">
<td>
<span
class="math inline">\(\Sigma(X-\overline{X})(Y-\overline{Y})\)</span>
</td>
<td>
37.9
</td>
</tr>
<tr scope="row">
<td>
<span class="math inline">\(cov_{xy}\)</span>
</td>
<td>
4.21
</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\begin{align}
  cov_{xy} &amp;= \frac{\Sigma(X-\overline{X})(Y-\overline{Y})}{N-1} \\
  &amp;= \frac{37.9}{9} = 4.21
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
  r &amp;= \frac{cov_{xy}}{s_xs_y} \\
  &amp;= \frac{4.21}{2.85 \times 1.97} = 0.75
\end{align}\]</span></p>
<p><strong>Pearson’s correlation analysis reveals a strong positive
relationship between anxiety and negative mood.</strong></p>
<blockquote>
<h4 id="reporting-3">Reporting</h4>
<p>‘A Pearson’s correlation analysis was conducted to examine the
relationship between anxiety and negative mood. The analysis revealed a
significant association between the variables, <em>r</em> = .75,
<em>N</em> = 10’</p>
</blockquote>
<div id="hypothesis-testing-and-pearsons-r" class="section level4">
<h4>Hypothesis testing and Pearson’s r</h4>
<p><span class="math display">\[\begin{align}
H_0&amp;: \rho = 0\ (null) \\
H_a&amp;: \rho \ne 0\ (two-tailed) \\
H_a&amp;: \rho &lt; 0\ or\ \\
H_a&amp;: \rho &lt; 0\ (one-tailed) \\
\end{align}\]</span></p>
</div>
<div id="significance-testing-of-r" class="section level4">
<h4>Significance testing of <span class="math inline">\(r\)</span></h4>
<p>Is our obtained correlation coefficient (<span
class="math inline">\(r\)</span>) significantly different from zero to
indicate that the two variables are not independent?</p>
<p><span class="math display">\[\begin{align}
  t &amp;= \frac{r\sqrt{N-2}}{{\sqrt{1-r^2}}} \\
  &amp;= \frac{0.75\sqrt{10-2}}{{\sqrt{1-0.75^2}}} \\
  &amp;= \frac{2.12}{0.66} = 3.21
\end{align}\]</span></p>
<blockquote>
<p><span class="math inline">\(t = 3.21(8), \alpha = 0.05\)</span></p>
</blockquote>
</div>
<div id="decision-making-6" class="section level4">
<h4>Decision Making</h4>
<p><span class="math display">\[\begin{align}
  t_{crit} &amp;= 2.306 \\
  t_{calc} &amp;= 3.21
\end{align}\]</span></p>
<blockquote>
<h3 id="reporting-4">Reporting</h3>
<p>‘As our calculated <em>t</em>-value is greater than the critical
<em>t</em>-value, we can reject the null hypothesis. The critical value
of <em>t</em> indicates that there is a significant positive
relationship between anxiety and negative mood (<em>r</em> = +0.75,
<em>n</em> = 10, <em>p</em> &lt; 0.05)’</p>
</blockquote>
</div>
</div>
<div id="predictedexplained-variance-r2" class="section level3 well">
<h3 class="well">Predicted/explained variance (<span
class="math inline">\(r^2\)</span>)</h3>
<div id="range-restriction" class="section level4">
<h4>Range restriction</h4>
<ul>
<li>Range restriction can be detected by examining the standard
deviations of variables.</li>
<li>Overly small standard deviations indicate that the variable is
restricted in range (i.e. people are all scoring at a similar point on
the scale).</li>
<li>Range restriction can cause an artificial change to the real
correlation (either reduced or inflated).</li>
<li>For example:
<ul>
<li>Overall there is a correlation between achievement test score and
college GPA scores of 0.65.</li>
<li>If we only examine the correlation between test scores and GPA for
those students who score 400 or more on the test, the association
reduces to 0.43.</li>
</ul></li>
</ul>
</div>
<div id="outliers" class="section level4">
<h4>Outliers</h4>
<p>An extreme score can have a dramatic influence on the correlation
coefficient.</p>
</div>
<div id="heterogeneous-subsamples" class="section level4">
<h4>Heterogeneous subsamples</h4>
<ul>
<li>Occurs when the data from two subgroups are mixed together.
(i.e. collapsed across gender)</li>
<li>Different groups could be characterised by different correlations
between the variables of interest. (agreeableness between men and
women)</li>
</ul>
</div>
</div>
</div>
<div id="week-7-regression" class="section level2 well">
<h2 class="well">Week 7: Regression</h2>
<div id="introduction-1" class="section level3 well">
<h3 class="well">Introduction</h3>
<ul>
<li>Using the regression line (line of best fit), we can predict
negative mood scores (Y / DV / criterion) based on anxiety (X / IV /
predictor).</li>
<li>In a bivariate analysis we can predict Y for any given value of X
statistically, via the use of the intercept (a) and slope (b).</li>
<li>A multiple analysis looks at the impact of the IV on several
DVs</li>
<li>We can estimate the value of Y from X via the scatterplot as
below:</li>
</ul>
<div class="float">
<img src="Images/RegEst.png" style="width:50.0%"
alt="Regression Estimate" />
<div class="figcaption">Regression Estimate</div>
</div>
</div>
<div id="components" class="section level3 well">
<h3 class="well">Components</h3>
<div id="slope" class="section level4">
<h4>Slope</h4>
<p>The slope describes the degree of difference (rise) in our Y
prediction where the value of X increases by 1.</p>
<p><span class="math display">\[\begin{align}
  b &amp;= \frac{cov_{XY}}{s_X^2}
\end{align}\]</span></p>
</div>
<div id="intercept" class="section level4">
<h4>Intercept</h4>
<p>The intercept predicts the point at which our line of regression
crosses the Y axis.</p>
<p><span class="math display">\[\begin{align}
  a &amp;= \overline{Y} - b\overline{X}
\end{align}\]</span></p>
</div>
<div id="equation" class="section level4">
<h4>Equation</h4>
<p>We use the below formula with a low and high point for X to
statistically estimate the respective values of Y.</p>
<p><span class="math display">\[\begin{align}
  \hat{Y} = bX + a
\end{align}\]</span></p>
</div>
<div id="standard-error-of-estimate" class="section level4">
<h4>Standard Error of estimate</h4>
<p>This value gives us the mean (?) distance between our plotted values
and the regression line.</p>
<p><span class="math display">\[\begin{align}
  S_{Y.X} = S_Y\sqrt{(1-r^2)}
\end{align}\]</span></p>
</div>
<div id="confidence-limits-95" class="section level4">
<h4>Confidence Limits (95%)</h4>
<p><span class="math display">\[\begin{align}
  CI_Y = \hat{Y} \pm (t_{a/2})(S_{Y.X})
\end{align}\]</span></p>
</div>
</div>
<div id="anxiety-vs-negative-mood-example" class="section level3 well">
<h3 class="well">Anxiety vs Negative Mood Example</h3>
<div id="data" class="section level4">
<h4>Data</h4>
<table class="table table-hover">
<thead>
<tr scope="row">
<th scope="col" colspan="2">
Scores
</th>
<th scope="col" colspan="2">
Deviations<BR>from mean
</th>
<th scope="col">
Products
</th>
</tr>
<tr scope="row">
<th scope="col">
Anxiety (<em>X</em>)
</th>
<th scope="col">
Negative<BR>mood (<em>Y</em>)
</th>
<th scope="col">
<span class="math inline">\(X - \overline{X}\)</span>
</th>
<th scope="col">
<span class="math inline">\(Y - \overline{Y}\)</span>
</th>
<th scope="col">
<span class="math inline">\((X-\overline{X})(Y-\overline{Y})\)</span>
</th>
</tr>
</thead>
<tbody>
<tr scope="row">
<td>
5
</td>
<td>
4
</td>
<td>
–0.9
</td>
<td>
–0.9
</td>
<td>
0.81
</td>
</tr>
<tr scope="row">
<td>
8
</td>
<td>
6
</td>
<td>
2.1
</td>
<td>
1.1
</td>
<td>
2.31
</td>
</tr>
<tr scope="row">
<td>
9
</td>
<td>
5
</td>
<td>
3.1
</td>
<td>
0.1
</td>
<td>
0.31
</td>
</tr>
<tr scope="row">
<td>
2
</td>
<td>
1
</td>
<td>
–3.9
</td>
<td>
–3.9
</td>
<td>
15.21
</td>
</tr>
<tr scope="row">
<td>
7
</td>
<td>
5
</td>
<td>
1.1
</td>
<td>
0.1
</td>
<td>
0.11
</td>
</tr>
<tr scope="row">
<td>
4
</td>
<td>
3
</td>
<td>
–1.9
</td>
<td>
–1.9
</td>
<td>
3.61
</td>
</tr>
<tr scope="row">
<td>
9
</td>
<td>
7
</td>
<td>
3.1
</td>
<td>
2.1
</td>
<td>
6.51
</td>
</tr>
<tr scope="row">
<td>
6
</td>
<td>
7
</td>
<td>
0.1
</td>
<td>
2.1
</td>
<td>
0.21
</td>
</tr>
</tbody>
</table>
<table class="table table-hover">
<thead>
<tr scope="row">
<th scope="col">
Measure
</th>
<th scope="col">
Value
</th>
</tr>
</thead>
<tbody>
<tr scope="row">
<td>
<span class="math inline">\(\overline{X}\)</span>
</td>
<td>
5.9
</td>
</tr>
<tr scope="row">
<td>
<span class="math inline">\(SD_X\)</span>
</td>
<td>
2.85
</td>
</tr>
<tr scope="row">
<td>
<span class="math inline">\(\overline{Y}\)</span>
</td>
<td>
4.9
</td>
</tr>
</tr>
<tr scope="row">
<td>
<span class="math inline">\(SD_Y\)</span>
</td>
<td>
1.97
</td>
</tr>
<tr scope="row">
<td>
<span
class="math inline">\(\Sigma(X-\overline{X})(Y-\overline{Y})\)</span>
</td>
<td>
37.9
</td>
</tr>
<tr scope="row">
<td>
<abbr title="Sum of products divided by N - 1"><span
class="math inline">\(cov_{xy}\)</span></abbr>
</td>
<td>
4.21
</td>
</tr>
</tbody>
</table>
</div>
<div id="steps-3" class="section level4 tabset">
<h4 class="tabset">Steps:</h4>
<div id="calculate-slope-b" class="section level5">
<h5>Calculate Slope (<span class="math inline">\(b\)</span>)</h5>
<p><span class="math display">\[\begin{align}
  b &amp;= \frac{cov_{XY}}{s_X^2} \\
  &amp;= \frac{4.21}{2.85^2} \\
  &amp;= 0.52
\end{align}\]</span></p>
</div>
<div id="calculate-intercept-a" class="section level5">
<h5>Calculate Intercept (<span class="math inline">\(a\)</span>)</h5>
<p><span class="math display">\[\begin{align}
  a &amp;= \overline{Y} - b\overline{X} \\
  &amp;= 4.9 - (0.52 \times 5.9) \\
  &amp;= 1.83
\end{align}\]</span></p>
</div>
<div id="calculateplot-regression-line-haty" class="section level5">
<h5>Calculate/Plot Regression Line (<span
class="math inline">\(\hat{Y}\)</span>)</h5>
<p>Where <span class="math inline">\(X = 0\)</span>:</p>
<p><span class="math display">\[\begin{align}
  \hat{Y} &amp;= bX + a \\
  &amp;= (0.52 \times 0) + 1.83 \\
  &amp;= 1.83
\end{align}\]</span></p>
<p>Where <span class="math inline">\(X = 9\)</span>:</p>
<p><span class="math display">\[\begin{align}
  \hat{Y} &amp;= bX + a \\
  &amp;= (0.52 \times 9) + 1.83 \\
  &amp;= 6.51
\end{align}\]</span></p>
<p>We now simply plot this line on the graph so that it passes through
the points (X = 0, Y = 1.832) and (X = 9, Y = 6.512).</p>
<div class="float">
<img src="Images/Regression.png" style="width:50.0%"
alt="Regression Line" />
<div class="figcaption">Regression Line</div>
</div>
</div>
<div id="calculate-seoe" class="section level5">
<h5>Calculate SEOE</h5>
<p><span class="math display">\[\begin{align}
  S_{Y.X} &amp;= S_Y\sqrt{(1-r^2)} \\
  &amp;= 1.97\sqrt{(1-0.56)} \\
  &amp;= 1.97\sqrt{0.44} \\
  &amp;= 1.97 \times 0.66 \\
  &amp;= 1.31
\end{align}\]</span></p>
</div>
<div id="confidence-limits-1" class="section level5 unnumbered">
<h5 class="unnumbered">Confidence Limits</h5>
<p>The critical value of <em>t</em>(<span
class="math inline">\(\alpha\)</span> = 0.05, df = 8) is 2.306.</p>
<p>Where <span class="math inline">\(X = 6\)</span>:</p>
<p><span class="math display">\[\begin{align}
  \hat{Y} &amp;= bX + a \\
  &amp;= (0.52 \times 6) + 1.83 \\
  &amp;= 3.18 + 1.83 \\
  &amp;= 5.01 \\
  \\
  CI_Y &amp;= \hat{Y} \pm (t_{a/2})(S_{Y.X}) \\
  &amp;= 5.01 \pm (2.306 \times 1.31) \\
  &amp;= 5.01 \pm 3.021 \\
  &amp;= 1.989\ to\ 8.031
\end{align}\]</span></p>
</div>
</div>
</div>
</div>
<div id="week-8-anova" class="section level2 well">
<h2 class="well">Week 8: ANOVA</h2>
<div id="introduction-2" class="section level3 well">
<h3 class="well">Introduction</h3>
<p>The differences between the t-test and ANOVA:</p>
<table>
<colgroup>
<col width="32%" />
<col width="20%" />
<col width="26%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th>t-test</th>
<th>Example</th>
<th>ANOVA</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One IV: two categorical levels</td>
<td>campus vs. cloud student</td>
<td>One IV: three or more categorical levels</td>
<td>Young vs. Middle Aged vs. Old</td>
</tr>
<tr class="even">
<td>One DV: continuous values</td>
<td>IQ score, exam results, unit results</td>
<td>One DV: Continuous values</td>
<td>IQ score, exam results, unit results</td>
</tr>
<tr class="odd">
<td>Examines:<br> - between group variance</td>
<td>-</td>
<td>Examines:<br> - between group, and<br> - within group variance</td>
<td>-</td>
</tr>
</tbody>
</table>
</div>
<div id="assumptions" class="section level3 well">
<h3 class="well">Assumptions</h3>
<ul>
<li>Homogeneity of Variance: equal spread of each group around the
mean</li>
<li>Normality: data is characterised by a normal distribution around the
mean</li>
<li>Independence of Observations: each score is not related to others.
If there is a relationship, scores are not random.</li>
<li>If these assumptions are violated, caution is required in
interpretation of the results.</li>
<li>A larger sample size overcomes the violation of assumptions.</li>
</ul>
</div>
<div id="sources-of-error" class="section level3 well">
<h3 class="well">Sources of error</h3>
<ul>
<li>Individual Differences such as sex, gender, personality, measurement
error,</li>
<li>Variability within group is called error variance,</li>
<li>Differences between groups due to chance or effect of treatment</li>
</ul>
</div>
<div id="f-statistic" class="section level3 well">
<h3 class="well">F-statistic</h3>
<ul>
<li>Reflects the proportion of variance between groups with the variance
within groups.</li>
<li>Tells us how many times larger the treatment effect is than the
error.</li>
<li>Is the difference between groups larger than the error between
groups</li>
<li>Compare <span class="math inline">\(F_{calc}\)</span> to <span
class="math inline">\(F_{crit}\)</span> to determine significance where
<span class="math inline">\(\alpha = 0.05\)</span>.</li>
</ul>
<p>If <span class="math inline">\(F_{calc} &gt; F_{crit}\)</span> we can
reject <span class="math inline">\(H_0\)</span></p>
<p><span class="math display">\[\begin{align}
  F &amp;= \frac{variance\ between\ groups}{variance\ within\ groups} \\
  OR \\
  F &amp;= \frac{treatment\ effect\ + difference\ due\ to\
chance}{difference\ due\ to\ chance}
\end{align}\]</span></p>
</div>
<div id="logic-of-anova" class="section level3 well">
<h3 class="well">Logic of ANOVA</h3>
<ul>
<li>Compares whether the difference between means is greater than the
difference expected by chance,</li>
<li>Denominator referred to as error variance as it represents
uncontrollable/random factors,</li>
<li>Numerator difference between mean (can also be due to chance or
uncontrollable factors),</li>
<li>Numerator also contains differences due to treatment,</li>
<li>If numerator treatment effect + error is larger than the
denominator, there is evidence that treatment is affecting between group
(mean) differences.</li>
</ul>
</div>
<div id="calculation-of-anova" class="section level3 well">
<h3 class="well">Calculation of ANOVA</h3>
<p>Steps:</p>
<ol style="list-style-type: decimal">
<li>Sums of Squares (distance of each score from the mean squared)</li>
<li>Degrees of Freedom</li>
<li>Mean Squares</li>
<li>F-value</li>
</ol>
</div>
<div id="age-vs.-happiness-notes-study-from-notes"
class="section level3 well">
<h3 class="well">Age vs. Happiness notes study from notes</h3>
<table class="table table-hover">
<tr scope="row">
<th scope="col">
</th>
<th scope="col">
Young People
</th>
<th scope="col">
Middle Aged People
</th>
<th scope="col">
Old People
</th>
</tr>
<tr scope="row">
<td>
</td>
<td>
6
</td>
<td>
7
</td>
<td>
8
</td>
</tr>
<tr scope="row">
<td>
</td>
<td>
7
</td>
<td>
8
</td>
<td>
9
</td>
</tr>
<tr scope="row">
<td>
</td>
<td>
7
</td>
<td>
5
</td>
<td>
8
</td>
</tr>
<tr scope="row">
<td>
</td>
<td>
6
</td>
<td>
7
</td>
<td>
8
</td>
</tr>
<tr scope="row">
<td>
</td>
<td>
5
</td>
<td>
6
</td>
<td>
9
</td>
</tr>
<tr scope="row">
<td>
Mean
</td>
<td>
6.2
</td>
<td>
6.6
</td>
<td>
8.4
</td>
</tr>
<tr scope="row">
<td>
Grand Mean
</td>
<td>
</td>
<td>
7.07
</td>
<td>
</td>
</tr>
</table>
<div id="sums-of-squares-distance-of-each-score-from-the-mean-squared"
class="section level4">
<h4>1. Sums of Squares (distance of each score from the mean
squared)</h4>
<div id="a.-calculate-ss_treatment" class="section level5">
<h5>a. Calculate <span
class="math inline">\(SS_{treatment}\)</span></h5>
<blockquote>
<p>Where:</p>
<p><span class="math inline">\(\overline{X}_j =\)</span> treatment group
mean,</p>
<p><span class="math inline">\(\overline{X}.. =\)</span> grand mean</p>
<p><span class="math inline">\(n =\)</span> group sample size</p>
<p><span class="math display">\[\begin{align}
SS_{treatment} &amp;= n\Sigma(\overline{X}_{j}-\overline{X}..)^2 \\
&amp;= 5([6.2-7.07]+[6.6-7.07]+[8.4-7.07]) \\
&amp;= 5(0.76 + 0.22 + 1.77) \\
&amp;= 5 \times 2.75 \\
&amp;= 13.75
\end{align}\]</span></p>
</blockquote>
</div>
<div id="b.-calculate-ss_error" class="section level5">
<h5>b. Calculate <span class="math inline">\(SS_{error}\)</span></h5>
<blockquote>
<p><em>Difference of each score from the mean of its group:</em></p>
<p>Where:</p>
<p><span class="math inline">\(X_{ij} =\)</span> score of each person in
group <span class="math inline">\(j\)</span>, and</p>
<p><span class="math inline">\(\overline{X}_j=\)</span> treatment group
mean</p>
<p><span class="math display">\[\begin{align}
SS_{error} &amp;= \Sigma(X_{ij}-\overline{X}_j)^2 \\
&amp;=[(6-6.2)^2+(7–6.2)^2+(7–6.2)^2+(6–6.2)^2+ \\
  &amp;(5–6.2)^2+(7–6.6)^2+(8–6.6)^2+(5–6.6)^2+ \\
  &amp;(7–6.6)^2+(6–6.6)^2+(8–8.4)^2+(9-8.4)^2+ \\
  &amp;(8–8.4)^2+(8–8.4)^2+(9–8.4)^2] \\
&amp;=0.04+0.64+0.64+0.04+1.44+0.16+1.96+ \\
  &amp;2.56+0.16+0.36+0.16+0.36+0.16+0.16+0.36 \\
&amp;=9.2
\end{align}\]</span></p>
</blockquote>
</div>
<div id="c.-calculate-ss_total" class="section level5">
<h5>c. Calculate <span class="math inline">\(SS_{total}\)</span></h5>
<blockquote>
<p><span class="math display">\[\begin{align}
SS_{total} &amp;= SS_{treatment} + SS_{error} \\
&amp;= 13.75+9.2 \\
&amp;= 22.95
\end{align}\]</span></p>
</blockquote>
</div>
</div>
<div id="degrees-of-freedom-1" class="section level4">
<h4>2. Degrees of Freedom</h4>
<blockquote>
<p>Where:</p>
<p><span class="math inline">\(k =\)</span> number of groups / levels in
IV</p>
<p><span class="math inline">\(n =\)</span> number of people in each
group / level</p>
<p><span class="math inline">\(N=\)</span> total number of participants
in study across all groups</p>
<p><span class="math display">\[\begin{align}
df_{treatment} &amp;= k-1 = 3-1 = 2 \\
df_{error} &amp;= k(n-1) = 3(5-1) = 12 \\
df_{total} &amp;= N-1 = 15-1 = 14 \\
\end{align}\]</span></p>
</blockquote>
</div>
<div id="ms_treatment-and-ms_error" class="section level4">
<h4>3. <span class="math inline">\(MS_{treatment}\)</span> and <span
class="math inline">\(MS_{error}\)</span></h4>
<blockquote>
<p>Dividing the <span class="math inline">\(SS_{treatment}\)</span> and
<span class="math inline">\(SS_{error}\)</span> by their respective
<span class="math inline">\(df\)</span> values:</p>
<p><span class="math display">\[\begin{align}
MS_{treatment} &amp;= \frac{SS_{treatment}}{df_{treatment}} =
\frac{13.75}{2} = 6.875 \\
MS_{error} &amp;= \frac{SS_{error}}{df_{error}} = \frac{9.2}{12} = 0.77
\\
\end{align}\]</span></p>
</blockquote>
</div>
<div id="calculate-f-value" class="section level4">
<h4>4. Calculate F-value</h4>
<blockquote>
<p><span class="math display">\[\begin{align}
F &amp;= \frac{MS_{treatment}}{MS_{error}} = \frac{6.875}{0.77} = 8.93
\\
\end{align}\]</span></p>
<ul>
<li>What does F mean?</li>
<li>Is it significant?</li>
</ul>
</blockquote>
</div>
<div id="effect-size-2" class="section level4">
<h4>5. Effect Size</h4>
<blockquote>
<ul>
<li>Tells us how much the total variability is caused by the difference
between treatments</li>
<li>Range from 0 to 1</li>
<li>Represented by eta squared (<span
class="math inline">\(\eta^2\)</span>)</li>
</ul>
<p><span class="math display">\[\begin{align}
\eta^2 &amp;= \frac{SS_{treat}}{SS{total}} = \frac{13.75}{22.95} = .60
\\
\end{align}\]</span></p>
</blockquote>
</div>
<div id="f-statistic-1" class="section level4">
<h4>F-statistic</h4>
<blockquote>
<ul>
<li>The F statistic tells us that the effect of the treatment (or the
difference between groups) is 8.93 times greater than the error within
groups.</li>
<li>You check to see if this is a significant difference using the table
at the back of your textbook.</li>
<li>Critical value for F (2, 12) at <span
class="math inline">\(\alpha\)</span> = .05 is 3.89.</li>
<li>Since our <span class="math inline">\(F_{calc} &gt;
F_{crit}\)</span> we can reject the null hypothesis.</li>
</ul>
</blockquote>
</div>
</div>
<div id="reporting-5" class="section level3 well">
<h3 class="well">Reporting</h3>
<p>A one-way ANOVA was conducted to examine whether there was a
significant difference in happiness between the young people, middle
aged people and old people groups. The analysis found a significant
difference between these groups, <em>F</em>(2, 12) = 6.875, <em>p</em>
&gt; .05, <span class="math inline">\(\eta^2_p = .60\)</span>.</p>
</div>
<div id="one-way-anova-summary-formulae" class="section level3 well">
<h3 class="well">One-way ANOVA Summary Formulae</h3>
<table class="table table-hover">
<tr scope="row">
<th scope="col">
Source
</th>
<th scope="col">
df
</th>
<th scope="col">
SS
</th>
<th scope="col">
MS
</th>
<th scope="col">
F
</th>
<th scope="col">
p
</th>
</tr>
<tr scope="row">
<td>
<abbr title="Between">Treatment</abbr>
</td>
<td>
<abbr title="k = no. of groups"><span
class="math inline">\(k-1\)</span></abbr>
</td>
<td>
<abbr title="n = Group sample size"><span
class="math inline">\(n\Sigma(\overline{X}_{j}-\overline{X}..)^2\)</span></abbr>
</td>
<td>
<span
class="math inline">\(\frac{SS_{treatment}}{df_{treatment}}\)</span>
</td>
<td>
<span class="math inline">\(\frac{MS_{treatment}}{MS_{error}}\)</span>
</td>
<td>
<abbr title="Significance level determined prior to test">.05</abbr>
</td>
</tr>
<tr scope="row">
<td>
<abbr title="Within">Error</abbr>
</td>
<td>
<abbr title="k = no. groups, n = Group sample size"><span
class="math inline">\(k(n-1)\)</span></abbr>
</td>
<td>
<span class="math inline">\(\Sigma(X_{ij}-\overline{X}_j)^2\)</span>
</td>
<td>
<span class="math inline">\(\frac{SS_{error}}{df_{error}}\)</span>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
Total
</td>
<td>
<abbr title="N = Total participants across all groups"><span
class="math inline">\(N-1\)</span></abbr>
</td>
<td>
<span class="math inline">\(SS_{treatment} + SS_{error}\)</span>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
Effect Size
</td>
<td>
<span class="math inline">\(\eta^2\)</span>
</td>
<td>
<span class="math inline">\(\frac{SS_{treat}}{SS_{total}}\)</span>
</td>
</tr>
</table>
</div>
</div>
<div id="week-9-post-hoc-tests" class="section level2 well">
<h2 class="well">Week 9: Post-hoc Tests</h2>
</div>
<div id="week-10-factorial-anova" class="section level2 well">
<h2 class="well">Week 10: Factorial ANOVA</h2>
<div id="introduction-3" class="section level3 well">
<h3 class="well">Introduction</h3>
<ul>
<li><p>Used to compare means across multiple groups when there is more
than one IV (factor) in the analysis:</p>
<ul>
<li>IV (categorical)</li>
<li>DV (Continuous)</li>
</ul></li>
</ul>
<div id="one-way-anova-review" class="section level4">
<h4>One-Way ANOVA (review)</h4>
<ul>
<li><p>Determining how ‘happiness’ scores (1 - 10) differ based on age
(A one-way comparison as there is only one IV)</p>
<ul>
<li>One IV: Age (3 levels - young, middle, old)</li>
<li>One DV: Happiness</li>
</ul></li>
</ul>
</div>
<div id="factorial-anova" class="section level4">
<h4>Factorial ANOVA</h4>
<ul>
<li><p>Determine differences in ‘happiness’ based on age AND gender (a
two-way comparison as there are two IVs)</p>
<ul>
<li><p>Two IVs:</p>
<ul>
<li>Age: 3 levels (young, middle, old)</li>
<li>Gender: 2 levels (male, female)</li>
</ul></li>
</ul></li>
</ul>
<p>A factorial ANOVA could be used to determine if the effects of age on
happiness are the same for males and females.</p>
</div>
<div id="main-interaction-effects" class="section level4">
<h4>Main &amp; Interaction Effects</h4>
<p>With a two-way ANOVA there are three possible effects:</p>
<ul>
<li><p>Main Effect 1: Overall effect of factor A (ignoring effects of
factor B)</p></li>
<li><p>Main Effect 2: Overall effect of factor B (ignoring effects of
factor A)</p></li>
<li><p>Interaction Effect: where the effect of one factor on the DV is
not the same at all levels of the other factor:</p>
<ul>
<li>Provides information about the relationship between the IVs and
DV</li>
<li>Are interpreted best with plots</li>
</ul></li>
</ul>
</div>
<div id="interaction-example" class="section level4">
<h4>Interaction Example</h4>
<p>Two-way ANOVA exploring the effect of temperature on cognitive
performance (recall) to determine if the effect is the same for males
and females.</p>
<ul>
<li>IV1: Temperature (3 levels: 10<span
class="math inline">\(^\circ\)</span>, 20<span
class="math inline">\(^\circ\)</span>, 30<span
class="math inline">\(^\circ\)</span>)</li>
<li>IV2: Gender (2 levels: male and female)</li>
<li>DV: Performance (recall)</li>
</ul>
<p>!Insert graph from handout!</p>
</div>
<div id="interactions" class="section level4">
<h4>Interactions</h4>
<ul>
<li>For females, performance improves with temperature</li>
<li>For males, temperature has no effect</li>
<li>The effect of IV1 (temperature) is not the same at all levels of IV2
(gender)</li>
<li>If the plot lines are parallel (do not cross over), there is no
interaction</li>
</ul>
</div>
<div id="main-effects" class="section level4">
<h4>Main Effects</h4>
<p>!Insert graph 2 from notes</p>
<ul>
<li>A main effect is the effect of IV1 on the DV (overall effect of
temperature on cognitive performance), while ignoring the effects of
IV2.</li>
<li>A main effect is the effect of IV2 on the DV (overall effect of
gender on cognitive performance), while ignoring the effects of
IV1.</li>
<li>Each IV can have a main effect of DV and an individual effect on
DV.</li>
</ul>
</div>
</div>
<div id="calculations" class="section level3 well">
<h3 class="well">Calculations</h3>
<table class="table table-hover">
<tr scope="row">
<th>
</th>
<th>
</th>
<th scope="col" colspan="2">
Stress
</th>
</tr>
<tr scope="row">
<td>
</td>
<td>
</td>
<td>
Low
</td>
<td>
High
</td>
<td>
<span class="math inline">\(Mean_A\)</span>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td rowspan="9">
Gender (B)
</td>
<td rowspan="3">
Males
</td>
<td>
74
</td>
<td>
72
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
78
</td>
<td>
70
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
71
</td>
<td>
74
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
<span class="math inline">\(Mean_{1B}\)</span>
</td>
<td>
74.33
</td>
<td>
72.00
</td>
<td>
73.17
</td>
<td>
</td>
</tr>
<tr scope="row">
<td rowspan="3">
Females
</td>
<td>
77
</td>
<td>
68
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
84
</td>
<td>
71
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
82
</td>
<td>
64
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
<span class="math inline">\(Mean_{2B}\)</span>
</td>
<td>
81.00
</td>
<td>
67.67
</td>
<td>
74.33
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
<span class="math inline">\(Mean_B\)</span>
</td>
<td>
77.67
</td>
<td>
69.83
</td>
<td>
73.75
</td>
<td>
&lt;- <span class="math inline">\(\overline{X}..\)</span>
</td>
</tr>
</table>
<div id="steps-4" class="section level4">
<h4>Steps</h4>
<ul>
<li><span class="math inline">\(n =\)</span> number of participants in
each cell (e.g. males with low anxiety = 3, there are 3 participants in
every cell),</li>
<li><span class="math inline">\(a =\)</span> levels of factor A</li>
<li><span class="math inline">\(b =\)</span> levels of factor B</li>
</ul>
<div id="calculate-ss_total" class="section level5">
<h5>Calculate <span class="math inline">\(SS_{total}\)</span></h5>
<p><span class="math display">\[\begin{align}
  SS_{total} &amp;= \Sigma(X-\overline{X}..)^2 \\
  &amp;= (6 – 7.33)^2 + (7 – 7.33)^2 + (9 –7.33)^2 + (8 – 7.33)^2 + (8 –
7.33)^2 + \\
    &amp;   (7 – 7.33)^2 + (4 – 7.33)^2 + (10 – 7.33)^2 + (5 – 7.33)^2 +
(9 – 7.33)^2 + \\
    &amp;   (6 – 7.33)^2 + (9 – 7.33)^2 \\
  &amp;=  1.7689 + 0.1089 + 2.7889 + 0.4489 + 0.4489 + 0.1089 + 11.0889
\\
    &amp;   + 7.1289 + 5.4289 + 2.7889 + 1.7689 + 2.7889 \\
  &amp;=  36.667
\end{align}\]</span></p>
</div>
<div id="calculate-ss_a" class="section level5">
<h5>Calculate <span class="math inline">\(SS_A\)</span></h5>
<p><span class="math display">\[\begin{align}
  SS_{A} &amp;= nb\Sigma(\overline{X}_A - \overline{X}..)^2 \\
  &amp;= 3 \times 2[(7.5 - 7.33)^2 + (7.16 - 7.33)^2] \\
  &amp;= 6 \times 0.0578 \\
  &amp;= 0.34 \\
\end{align}\]</span></p>
</div>
<div id="calculate-ss_b" class="section level5">
<h5>Calculate <span class="math inline">\(SS_B\)</span></h5>
<p><span class="math display">\[\begin{align}
  SS_{B} &amp;= na\Sigma(\overline{X}_A - \overline{X}..)^2 \\
  &amp;= 3 \times 2[(6.33 - 7.33)^2 + (8.33 - 7.33)^2] \\
  &amp;= 6 \times 2 \\
  &amp;= 12 \\
\end{align}\]</span></p>
</div>
<div id="calculate-ss_cells" class="section level5">
<h5>Calculate <span class="math inline">\(SS_{cells}\)</span></h5>
<p><span class="math display">\[\begin{align}
  SS_{cells} &amp;= n\Sigma(\overline{X}_A - \overline{X}..)^2 \\
  &amp;= 3 \times [(7.67 - 7.33)^2 + (7.33 - 7.33)^2 + (5 - 7.33)^2 +
(9.33 - 7.33)^2] \\
  &amp;= 3 \times 9.5445 \\
  &amp;= 28.6335
\end{align}\]</span></p>
</div>
<div id="calculate-ss_ab" class="section level5">
<h5>Calculate <span class="math inline">\(SS_{A*B}\)</span></h5>
<p><span class="math display">\[\begin{align}
  SS_{AB} &amp;= SS_{cells} – SS_A – SS_B \\
  &amp;= 28.6335 – 0.34 – 12 \\
  &amp;= 16.3
\end{align}\]</span></p>
</div>
<div id="calculate-ss_error" class="section level5">
<h5>Calculate <span class="math inline">\(SS_{error}\)</span></h5>
<p><span class="math display">\[\begin{align}
  SS_{error} &amp;= SS_{total} – SS_{cells} \\
  &amp;= 36.667 – 28.6335 \\
  &amp;= 8
\end{align}\]</span></p>
</div>
</div>
<div id="anova-summary-table" class="section level4 well">
<h4 class="well">ANOVA Summary Table</h4>
<table class="table table-hover">
<tr scope="row">
<th scope="col">
df
</th>
<th scope="col">
<abbr title="Sum of Squares">SS</abbr>
</th>
<th scope="col">
<abbr title="Mean of Squares">MS</abbr>
</th>
<th scope="col">
F
</th>
<th scope="col">
p
</th>
</tr>
<tr scope="row">
<td>
A (gender)
</td>
<td>
1
</td>
<td>
0.34
</td>
<td>
0.34
</td>
<td>
0.34
</td>
<td>
0.05
</td>
</tr>
<tr scope="row">
<td>
B (anxiety)
</td>
<td>
1
</td>
<td>
12
</td>
<td>
12
</td>
<td>
12
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
AB (interaction)
</td>
<td>
1
</td>
<td>
16.3
</td>
<td>
16.3
</td>
<td>
16.3
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
Error
</td>
<td>
8
</td>
<td>
8
</td>
<td>
1
</td>
<td>
</td>
<td>
</td>
</tr>
<tr scope="row">
<td>
Total
</td>
<td>
11
</td>
<td>
36.6
</td>
</tr>
</table>
</div>
</div>
<div id="reporting-6" class="section level3 well">
<h3 class="well">Reporting</h3>
<p>A two-way ANOVA was conducted to examine the effect of instruction
(self-paced or structured) and personality (internal or external) on
exam performance. The analysis showed a significant interaction effect,
<em>F</em>(1, 16) = 5.57, <em>p</em> = .031, <span
class="math inline">\(\eta^2_p\)</span> = .26. Internally driven
individuals scored higher on the exam when they were provided with a
self-paced learning program (<em>M</em> = 82.80, <em>SD</em> = 11.30) as
opposed to a structured learning program (<em>M</em> = 75.20,
<em>SD</em> = 5.93). Externally driven individuals scored higher on the
exam when they were provided with a structured learning program
(<em>M</em> = 82.20, <em>SD</em> = 6.61) as opposed to a self-paced
learning program (<em>M</em> = 72.40, <em>SD</em> = 8.08).</p>
<p>A two-way ANOVA was conducted to examine the effect of maths anxiety
(low or high) and counselling (yes or no) on exam performance. The
analysis showed a significant main effect for maths anxiety,
<em>F</em>(1, 28) = 5.78, <em>p</em> = .023, <span
class="math inline">\(\eta^2_p\)</span> = .17. On average, students in
the low anxiety group (<em>M</em> = 81.00, <em>SD</em> = 10.30)
performed better on the exam than students in the high anxiety group
(<em>M</em> = 72.50, <em>SD</em> = 10.24).</p>
</div>
<div id="two-way-anova-summary-table-formulae"
class="section level3 well">
<h3 class="well">Two-way ANOVA Summary Table (Formulae)</h3>
<table class="table table-hover">
<tr scope="row">
<th scope="col">
Source
</th>
<th scope="col">
df
</th>
<th scope="col">
<abbr title="Sum of Squares">SS</abbr>
</th>
<th scope="col">
<abbr title="Mean of Squares">MS</abbr>
</th>
<th scope="col">
F
</th>
<th scope="col">
p
</th>
</tr>
<tr scope="row">
<td>
Factor A
</td>
<td>
<abbr title="a = # of levels in factor A"><span
class="math inline">\(a-1\)</span></abbr>
</td>
<td>
<abbr title="n = # of participants per cell, b = # of levels in B"><span
class="math inline">\(nb\Sigma(\overline{X}_A -
\overline{X}..)^2\)</span><abbr></abbr>
</td>
<td>
<span class="math inline">\(\frac{SS_A}{df_A}\)</span>
</td>
<td>
<span class="math inline">\(\frac{MS_A}{MS_{error}}\)</span>
</td>
<td>
0.05
</td>
</tr>
<tr scope="row">
<td>
Factor B
</td>
<td>
<abbr title="b = # of levels in factor B"><span
class="math inline">\(b-1\)</span></abbr>
</td>
<td>
<abbr title="n = # of participants per cell, a = # of levels in A"><span
class="math inline">\(na\Sigma(\overline{X}_A -
\overline{X}..)^2\)</span></abbr>
</td>
<td>
<span class="math inline">\(\frac{SS_B}{df_B}\)</span>
</td>
<td>
<span class="math inline">\(\frac{MS_B}{MS_{error}}\)</span>
</td>
<td>
 
</td>
</tr>
<tr scope="row">
<td>
A*B (interaction)
</td>
<td>
<abbr title="(a-1) * (b-1)"><span class="math inline">\(df_A \times
df_B\)</span></abbr>
</td>
<td>
<span class="math inline">\(SS_{cells} – SS_A – SS_B\)</span>
</td>
<td>
<span class="math inline">\(\frac{SS_{AB}}{df_{AB}}\)</span>
</td>
<td>
<span class="math inline">\(\frac{MS_{AB}}{MS_{error}}\)</span>
</td>
<td>
 
</td>
</tr>
<tr scope="row">
<td>
Error
</td>
<td>
<span class="math inline">\(df_{total} - df_A - df_B - df_{AB}\)</span>
</td>
<td>
<span class="math inline">\(SS_{total} – SS_{cells}\)</span>
</td>
<td>
<span class="math inline">\(\frac{SS_{error}}{df_{error}}\)</span>
</td>
<td>
 
</td>
<td>
 
</td>
</tr>
<tr scope="row">
<td>
Total
</td>
<td>
<abbr title="N = total # of participants"><span
class="math inline">\(N-1\)</span></abbr>
</td>
<td>
<abbr title="Sum of squares for each value in the study"><span
class="math inline">\(\Sigma(X-\overline{X}..)^2\)</span></abbr>
</td>
<td>
 
</td>
<td>
 
</td>
<td>
 
</td>
</tr>
<tr scope="row">
<td colspan="5">
<abbr title="omitted from summary like any Sum of Squares value"><span
class="math inline">\(SS_{cells} = n\Sigma(\overline{X}_A -
\overline{X}..)^2\)</span></abbr>
</td>
<td>
 
</td>
<td>
 
</td>
<td>
 
</td>
<td>
 
</td>
</tr>
</table>
</div>
</div>
<div id="formulae" class="section level2 well">
<h2 class="well">Formulae</h2>
<div id="variance" class="section level4 well">
<h4
class="well"><abbr title="Variance tells you the degree of spread in your data set. The more spread the data, the larger the variance is in relation to the mean.">Variance</abbr></h4>
<p><span class="math inline">\(s^2 =
\frac{\Sigma(X-\overline{X})^2}{N-1}\)</span></p>
<p><code>var(mean)</code></p>
</div>
<div id="standard-deviation" class="section level4 well">
<h4 class="well">Standard Deviation</h4>
<p><span class="math inline">\(s =
\sqrt{\frac{\Sigma(X-\overline{X})^2}{N-1}}\)</span></p>
<p><code>sd(X)</code></p>
</div>
<div id="confidence-limits-on-z-upper-and-lower"
class="section level4 well">
<h4 class="well">95% Confidence limits on z (upper and lower)</h4>
<p><span class="math inline">\(X = \mu \pm 1.96\sigma\)</span></p>
</div>
<div id="z-score" class="section level4 well">
<h4
class="well"><abbr title="Gives the Standard Deviation of a set of data as a standardised number">Z
Score</abbr></h4>
<p><span class="math inline">\({z = \frac{X -
\overline{X}}{\sigma}}\)</span></p>
<p>given an area, find the boundary value that determines this area.</p>
<pre><code>## [1] 100</code></pre>
</div>
<div id="formulae-summary" class="section level4 well">
<h4 class="well">Formulae Summary</h4>
<table>
<colgroup>
<col width="17%" />
<col width="51%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th>Purpose</th>
<th align="center">Formula</th>
<th>R Input</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variance</td>
<td align="center"><span class="math inline">\(s^2 =
\frac{\Sigma(X-\overline{X})}{N-1}\)</span></td>
<td><code>var(X)</code></td>
</tr>
<tr class="even">
<td>Std Deviation</td>
<td align="center"><span class="math inline">\(s =
\sqrt{\frac{\Sigma(X-\overline{X})}{N-1}}\)</span></td>
<td><code>sd(x)</code></td>
</tr>
<tr class="odd">
<td>z-score</td>
<td align="center"><span class="math inline">\({z = \frac{X -
\overline{X}}{\sigma}}\)</span></td>
<td>See R Function Summary</td>
</tr>
</tbody>
</table>
</div>
<div id="r-function-summary" class="section level4 well">
<h4 class="well">R function summary</h4>
<table>
<colgroup>
<col width="26%" />
<col width="73%" />
</colgroup>
<thead>
<tr class="header">
<th>Purpose</th>
<th>R Input</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Density</td>
<td><code>dnorm(x, mean = 0, sd = 1, log = FALSE)</code></td>
</tr>
<tr class="even">
<td>Distribution Function</td>
<td><code>pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)</code></td>
</tr>
<tr class="odd">
<td>Quantile Function</td>
<td><code>qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)</code></td>
</tr>
<tr class="even">
<td>Random Deviates</td>
<td><code>rnorm(n, mean = 0, sd = 1)</code></td>
</tr>
</tbody>
</table>
</div>
<div id="confidence-limits-on-z" class="section level4 well">
<h4 class="well">Confidence limits on z</h4>
<p><span class="math inline">\(X = \mu \pm 1.96\sigma\)</span></p>
</div>
<div id="chi-square" class="section level4 well">
<h4 class="well">Chi-Square</h4>
<div id="goodness-of-fit-1-way-classification" class="section level5">
<h5>Goodness of Fit / 1 Way Classification</h5>
<p><span class="math inline">\(\chi^2 =
\sum\frac{(O-E)^2}{E}\)</span></p>
<p><span class="math inline">\(df = C - 1\)</span></p>
</div>
<div id="independence-test-2-way-classification" class="section level5">
<h5>Independence Test / 2 Way Classification</h5>
<p><span class="math inline">\(E_{ij} =
\frac{R_{i}C_{j}}{N}\)</span></p>
<p><span class="math inline">\(df = (R-1)(C-1)\)</span></p>
</div>
<div id="sample-size" class="section level5">
<h5>Sample Size</h5>
<p><span class="math inline">\(\Phi =
\sqrt{\frac{\chi^2}{N}}\)</span></p>
</div>
</div>
<div id="linear-relationships" class="section level3 well">
<h3 class="well">Linear Relationships</h3>
<div id="correlation" class="section level4">
<h4>Correlation</h4>
<p><span class="math inline">\(r =
\frac{cov_{xy}}{s_{x}s_{y}}\)</span></p>
<p><span class="math inline">\(df = N-2\)</span></p>
</div>
<div id="covariance-1" class="section level4">
<h4>Covariance</h4>
<p><span
class="math inline">\(\frac{(X-\overline{X})(Y-\overline{Y})}{N-1}\)</span></p>
</div>
<div id="significance-of-r" class="section level4">
<h4>Significance of r</h4>
<p><span class="math inline">\(t =
\frac{r\sqrt{N-2}}{\sqrt{(1-r^2)}}\)</span></p>
</div>
<div id="regression" class="section level4">
<h4>Regression</h4>
<table>
<thead>
<tr class="header">
<th>Purpose</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>General Equation</td>
<td><span class="math inline">\(\hat{Y} = bX - a\)</span></td>
</tr>
<tr class="even">
<td>Slope</td>
<td><span class="math inline">\(r =
\frac{cov_{xy}}{s_{x}^2}\)</span></td>
</tr>
<tr class="odd">
<td>Intercept</td>
<td><span class="math inline">\(a = \overline{Y} -
b\overline{X}\)</span></td>
</tr>
</tbody>
</table>
<details>
<summary>
<strong>Formulae Chart</strong>
</summary>
<div class="float">
<img src="images/HPS201/Formulae/HPS201.formulae.svg"
alt="Formulae Chart" />
<div class="figcaption">Formulae Chart</div>
</div>
</details>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
